---
title: CV
name: Fei
surname: Gu
position: "Ph.D Student"
address: "Institute of Psychology, Chinese Academy of Sciences"
www: flashsherlock.github.io
email: "guf@psych.ac.cn"
orcid: 0000-0001-7253-9097
github: flashsherlock
googlescholar: iMfym1QAAAAJ
headcolor: 414141 # use black color
date: "`r format(Sys.time(), '%m-%d-%Y')`"
csl: apa-cv.csl # change this if you want to use other citation styles
# biblio-style: apa
output: 
  vitae::awesomecv:
    # citation_package: biblatex
    keep_tex: true
    pandoc_args: ["--lua-filter=lua/strong.lua"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Education

```{r}
tribble(
  ~ Degree,
  ~ Advisor,
  ~ Year,
  ~ Institution,
  ~ Where,
  "PhD Student, Cognitive Neuroscience",
  "Advisor: Dr. Wen Zhou",
  "09/2019-present",
  "Institute of Psychology, Chinese Academy of Sciences",
  "Beijing, China",
  "Bachelor of Science, Psychology, Minor in Biology",
  "Thesis: Implicit Acquisition of Odor Valence",
  "09/2015-07/2019",
  "Beijing Normal University",
  "Beijing, China",
) %>%
  detailed_entries(
    what = Degree,
    when = Year,
    with = Institution,
    where = Where,
    why = Advisor
  )
```

# Awards and Grants

```{r}
tribble(
  ~ Year,
  ~ Name,
  ~ Institution,
  ~ Supp,
  ~ Amount,
  '2020', "Merit Student","Chinese Academy of Sciences",NA,NA,
  '2019', "Student's Innovation Training Program","Chinese Academy of Sciences",NA,'$1500',
  '2019', "Beisen Scholarship","Beijing Beisen Cloud Computing Co Ltd",NA,'$150',
  '2019', "The Academic Scholarship","Beijing Normal University",NA,'$150',
  '2017,2018', "The Competition Scholarship","Beijing Normal University",NA,'$670',
  '2018', "Hornorable Mention at The Interdisciplinary Contest in Modeling","The Consortium for Mathematics and its Applications (COMAP)",NA,NA,
  '2017', "Bronze Medal at the iGEM 2017 Competition","International Genetically Engineered Machine (iGEM) Foundation",NA,NA,
  '2016', "Beijing Student's Innovation and Entrepreneurship Training Program","Beijing Municipal Education Commission",NA,'$1500',
  '2016-2018', "Jingshi Scholarship","Beijing Normal University",NA,'$1950',
) %>%
  detailed_entries(
    where = Year,
    with = Name,
    what = Institution,
    why = Supp,
    when = Amount
  ) 
```

# Research Interests

Olfaction; amygdala; odor representation; fMRI

# Research outputs

## Articles

```{r}
bibliography_entries("Publication.bib") %>% dplyr::arrange(desc(issued))
```

## Presentations

```{r}
bibliography_entries("Presentations.bib") %>% dplyr::arrange(desc(issued))
```
