version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /Volumes/WD_D/gufei/seafile/mysql:/var/lib/mysql  #Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    ports:
      - "6025:80"
    networks:
      - seafile-net
            
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "6026:80"
#      - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /Volumes/WD_D/gufei/seafile/data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=mail # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=password     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether use letsencrypt to generate cert.
      - SEAFILE_SERVER_HOSTNAME=localhost:6026 # Specifies your host name.
    depends_on:
      - db
      - memcached
      - onlyoffice
    networks:
      - seafile-net

networks:
  seafile-net:

# add these lines to seahub_settings.py
# ENABLE_ONLYOFFICE = True
# VERIFY_ONLYOFFICE_CERTIFICATE = False
# ONLYOFFICE_APIJS_URL = 'http://localhost:6025/web-apps/apps/api/documents/api.js'
# ONLYOFFICE_FILE_EXTENSION = ('doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'odt', 'fodt', 'odp', 'fodp', 'ods', 'fods')
# ONLYOFFICE_EDIT_FILE_EXTENSION = ('docx', 'pptx', 'xlsx', 'doc', 'xls', 'ppt')