# cd /Users/mac/Documents/GitHub/fMRIdata/learning/mac_settings/
cp ./.cshrc ~
cp ./.tcshrc ~
cp ./.vimrc ~
cp ./.zshrc ~
cp ./.vimrc_bk ~
cp ./.tmux.conf ~
cp ./startup.m ~/matlab/
cp ./powerline-shell-config.json ~/.config/powerline-shell/config.json
