sub		   = 's01'
fshome     = '/Applications/freesurfer/7.1.1/';
subdir     = '/Volumes/WD_D/gufei/consciousness/electrode/use/s01/';
mrfile     = [subdir sub '_MRI.nii'];
system(['export FREESURFER_HOME=' fshome '; ' ...
'source $FREESURFER_HOME/SetUpFreeSurfer.sh; ' ...
'mri_convert -c -oc 0 0 0 ' mrfile ' ' [subdir '/tmp.nii'] '; ' ...
'recon-all -i ' [subdir '/tmp.nii'] ' -s ' 'freesurfer' ' -sd ' subdir ' -all'])
