---
title: "Behavior"
author: "Fei"
date: "2020/9/6"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, tidy=F,fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(openxlsx)
library(dplyr)
library(anipaths)
```


```{r}
# setwd("/home/gufei/Desktop/")
filename <- dir(pattern = "*.xlsx")
for (f in filename) {
  # 读取xlsx并取出有用的3列
  data <- subset(read.xlsx(f),type==108 & time>=0, select=c("time","data1","data2"))
  
  # 修改列名称
  names(data)[2:3] <- c("x","y")
  # 时间转化为ms，并且四舍五入
  data <- mutate(data,time=round(time/1000))
  
  # 用日期作为变量名
  result <- paste0("data",substring(f,5,8))
  # 将得到的结果放到对应的变量中
  assign(result,data)
  
}
save(list = ls(pattern='data07*'),file="Behavior4days.RData")
# 保存到csv中
write.csv(data0708,"data0708.csv",row.names = F)
write.csv(data0709,"data0709.csv",row.names = F)
write.csv(data0715,"data0715.csv",row.names = F)
write.csv(data0716,"data0716.csv",row.names = F)
```


试验画出路径，结果发现需要每个点生成一张图，会因为内存不足而出问题，所以改用matlab的comet画图。

```{r}
mdata=data0708[1:500,]
p <- plot_ly(mdata,x='x',y='y',frame='time',type = 'scatter',mode='markers')
htmlwidgets::saveWidget(as_widget(p),"graph.html")
# 全部的太大了没法画，内存不够
animate_paths(paths = mdata, 
              delta.t = 40,
              coord = c("x", "y"),
              Time.name = "time",
              whole.path = TRUE,)
```


```{r}
library(anipaths)
# 样例的代码
vultures$POSIX <- as.POSIXct(vultures$timestamp, tz = "UTC")
vultures_paths <- vultures[format(vultures$POSIX, "%Y") == 2009, ] ## limit attention to 2009
delta.t <- "day"
# animate_paths(paths = vultures_paths, 
#               delta.t = delta.t,
#               coord = c("location.long", "location.lat"),
#               Time.name = "POSIX",
#               ID.name = "individual.local.identifier")
animate_paths(paths = vultures_paths, 
              delta.t = delta.t,
              coord = c("location.long", "location.lat"),
              Time.name = "POSIX",
              ID.name = "individual.local.identifier", 
              whole.path = TRUE, tail.length = 0)
# behaviors <- c("exploratory", "directed", "stationary")
# set.seed(1)
# vultures_paths$behavior <- 
#   unlist(sapply(unique(vultures_paths$individual.local.identifier), function(id){
#     v_id <- vultures_paths[vultures_paths$individual.local.identifier == id, ]
#     switches <- c(0, sort(sample(1:nrow(v_id), 2)), nrow(v_id))
#     rep(behaviors[sample(1:3, 3)], diff(switches))
#   }))
```

