---
title: "Voxel_group"
author: "Fei"
date: "`r Sys.time()`"
output: html_document
params:
    path: "/Volumes/WD_F/gufei/7T_odor"
    sub: "results"
    thr: 2.051831
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = FALSE,tidy=F,fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
library(ggrepel)
library(R.matlab)
library(plyr)
library(dplyr)
library(tidyr)
library(ggprism)
library(patchwork)
library(gridExtra)
library(plotly)
ggthemr('fresh',layout = "clean")
```

# Functions and parameters
```{r}
####################################################
# function to load txt file
####################################################
extractdata <- function(path,sub,txtname){
  data <- read.table(file.path(path,sub,txtname))
  # add subject name to the first column
  data <- cbind(rep(sub,times=nrow(data)),data)
  return(data)
}
####################################################
# function to calculate activated voxels
####################################################
calcact <- function(results,roilist,threshold){
  c <- 4
  data <- data.frame(matrix(ncol = 3+c*2, nrow = 0))
  
  for (roi_i in names(roilist)) {
  # select ROI
  roi_label <- roilist[[roi_i]]
  results_r <- subset(results,roi %in% roi_label,select = c((6+c):(5+c+c)))
  subs <- subset(results,roi %in% roi_label,select = 1)
  # check if activated
  results_r <- ifelse(abs(results_r)>threshold,1,0)
  act <- cbind(subs,rep(1,times=nrow(subs)),results_r)
  # calculate number and ratio
  number <- aggregate(.~sub, act, sum)
  ratio <- aggregate(.~sub, act, mean)
  # add roi name
  act <- cbind(rep(roi_i,times=nrow(number)),number,ratio[c(3:(2+c))])
  data <- rbind(data,act)
  }
  # change column names
  names(data)[1:3] <- c("roi","sub","all")
  names(data)[c(4:(3+c))] <- str_replace(names(data)[c(4:(3+c))],"t_","c_")
  names(data)[c((4+c):(3+c+c))] <- str_replace(names(data)[c((4+c):(3+c+c))],"t_","r_")
  # change to percentage
  data[c((4+c):(3+c+c))] <- data[c((4+c):(3+c+c))]*100
  data <- reshape2::melt(data,c("sub","roi"))
  return(data)
}
####################################################
# function to calculate mean values
####################################################
calmean <- function(results,roilist, threshold = 0){
  c <- 4
  data <- data.frame(matrix(ncol = 3+c, nrow = 0))
  
  for (roi_i in names(roilist)) {
  # select ROI
  roi_label <- roilist[[roi_i]]
  results_r <- subset(results,roi %in% roi_label,select = c(6:(5+c)))
  subs <- subset(results,roi %in% roi_label,select = 1)
  # absolute value
  results_r <- abs(results_r)
  act <- cbind(subs,results_r)
  # threshold t value
  results_t <- subset(results,roi %in% roi_label,select = c((6+c):(5+c+c)))
  index <- apply(abs(results_t),1,function(x) any(x>threshold))
  # significant voxels only
  act <- act[index]
  # calculate mean value
  # m <- aggregate(.~sub, act, mean)
  m <- describeBy(act[,-1],list(act$sub),mat=T)
  m <- subset(m,select = c("group1","mean","se"))
  m <- cbind(str_remove(rownames(m),"1"),m)
  # add roi name
  act <- cbind(rep(roi_i,times=nrow(m)),m)
  data <- rbind(data,act)
  }
  # change column names
  names(data)[1:3] <- c("roi","voxels","sub")
  return(data)
}
# odor pairs
opair <- c("car-lim","cit-lim","tra-lim","ind-lim")
# roi labels
roi_name <- c("Amy","BaLa","CeMe","Cortical",'Pir_new','Pir_old','APC_new','APC_old','PPC')
A <- c(1,3,5,6,7,8,9,15)
B <- c(1,3,8,15)
Ce <- c(5,6)
Co <- c(7,9)
Pn <- c(21,22,29)
Po <- c(21,22)
An <- c(21,29)
Ao <- 21
PPC <- 22
roilist <- list(Amy=A,BaLa=B,CeMe=Ce,Cortical=Co,Pir_new=Pn,Pir_old=Po,APC_new=An,APC_old=Ao,PPC=PPC)
roimarker <- c(1,3,5,6,7,8,9,15,21,22,29)
roilabels <- c("La","Ba","Ce","Me","Co","BM","CoT","Para","APc","PPc","APn")
# colors
gf_color <- c("#f0803b","#56a2d4","#ECB556","#55b96f","#777DDD")
```


```{r}
cat(params$sub)
# sub x y z roi 4mean 4t-value
results <- data.frame(matrix(ncol = 1+12, nrow = 0))
# extract group results
results <- rbind(results,extractdata(params$path,"group",paste0("stats_",params$sub,".txt")))
names(results) <- c("sub","x","y","z","roi",paste("m",opair,sep = "_"),paste("t",opair,sep = "_"))
results <- as.data.table(results)
```

# Activated voxels
```{r fig.height=5, fig.width=12}
data_act <- calcact(results,roilist,params$thr)
s <- c("all",paste0("c_",opair))
data_act_mean <- describeBy(data_act$value,list(data_act$variable,data_act$roi),mat=T)
data_act_mean <- subset(data_act_mean,select = c(group1,group2,mean,se))
names(data_act_mean) <- c("voxels","roi","mean","se")
data_act_mean <- mutate(data_act_mean,roi = factor(roi,levels=roi_name))
datachosen <- subset(data_act_mean,voxels %in% s)
datachosen <- mutate(datachosen,voxels = factor(voxels,levels=s,labels = c("all",opair)))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Count',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color)+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)

# ratio
s <- c(paste0("r_",opair))
datachosen <- subset(data_act_mean,voxels %in% s)
datachosen <- mutate(datachosen,voxels = factor(voxels,levels=s,labels = opair))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Percentage',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color[2:5])+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)
```

# Mean value
```{r fig.height=5, fig.width=12}
data_mean <- calmean(results,roilist)
s <- c(paste0("m_",opair))
datachosen <- mutate(data_mean,voxels = factor(voxels,levels=s,labels = opair))
datachosen <- mutate(datachosen,roi = factor(roi,levels=roi_name))
datachosen <- subset(datachosen,voxels%in%c("car-lim","cit-lim"))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Mean difference',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color[2:5])+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)

# activated only
data_mean <- calmean(results,roilist,params$thr)
s <- c(paste0("m_",opair))
datachosen <- mutate(data_mean,voxels = factor(voxels,levels=s,labels = opair))
datachosen <- mutate(datachosen,roi = factor(roi,levels=roi_name))
datachosen <- subset(datachosen,voxels%in%c("car-lim","cit-lim"))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Mean difference',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color[2:5])+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)
```

```{r}
# select ROI
c <- 4
results_r <- subset(results,roi %in% c(21,22,29),select = c(5:(5+c)))
# threshold t value
results_t <- subset(results,roi %in% c(21,22,29),select = c((6+c):(5+c+c)))
index <- apply(abs(results_t),1,function(x) any(x>params$thr))
# significant voxels only
act <- results_r[index,1:3]
# add roi name
act <- mutate(abs(act),roinew = if_else(roi == 22, "PPC","APC"))
# APC_new
bruceR::MANOVA(act,between = "roinew", within = "pairs",
               dvs = c("m_car-lim","m_cit-lim"),dvs.pattern = "m_(.*)")%>%
  EMMEANS("pairs",by = "roinew")
# APC_old
bruceR::MANOVA(subset(act,roi != 29),between = "roinew", within = "pairs",
               dvs = c("m_car-lim","m_cit-lim"),dvs.pattern = "m_(.*)")%>%
  EMMEANS("pairs",by = "roinew")
```

```{r fig.height=9, fig.width=9}
# add labels to roi
results[,roi:=factor(roi,levels = sort(unique(results$roi)),labels=roilabels)]
# reverse xy
results$x <- -results$x
results$y <- -results$y
# absolute difference and x
results_abs<- cbind(abs(results[,2]),results[,3:5],abs(results[,6:13]))
# 3d scatter plot
# lim-cit
p1 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~abs(`m_cit-lim`),size = I(30),symbol = I("square"), hovertemplate = paste('%{marker.color:.2f}'))
# lim-car
p2 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~abs(`m_car-lim`),size = I(30),symbol = I("square"), hovertemplate = paste('%{marker.color:.2f}'))
# activated only average voxels in the same coordinate
# cit-lim
p3 <- plot_ly(results_abs[`t_cit-lim`>params$thr,lapply(.SD, mean),.SDcol=5:9,by=c("x","y","z","roi")],
              x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~`m_cit-lim`,size = I(30),symbol = I("square"), hovertemplate = paste('%{marker.color:.2f}'))
# car-lim
p4 <-plot_ly(results_abs[`t_car-lim`>params$thr,lapply(.SD, mean),.SDcol=5:9,by=c("x","y","z","roi")],
             x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~`m_car-lim`,size = I(30),symbol = I("square"), hovertemplate = paste('%{marker.color:.2f}'))
# cit-lim-car-lim
p5 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~(abs(`m_cit-lim`)-abs(`m_car-lim`)),
        size = I(30),symbol = I("square"), hovertemplate = paste('%{marker.color:.2f}'))%>%colorbar(title = "struc-quality")
# normalized
p6 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~(abs(`m_cit-lim`)-abs(`m_car-lim`))/(abs(`m_cit-lim`)+abs(`m_car-lim`)),size = I(30),symbol = I("square"), hovertemplate = paste('%{marker.color:.2f}'))%>%colorbar(title = "struc-quality-norm")
htmltools::tagList(list(p1, p2, p3, p4, p5, p6))
```

```{r fig.height=9, fig.width=9}
# Pir and Amy
for (roi in c("Pir","Amy","All")) {
  # pir
  if (roi == "Pir")
    results_select <- subset(results_abs,roi %in% c("APc","PPc","APn"))
  else if (roi == "Amy")
    results_select <- subset(results_abs,roi %in% c("La","Ba","Ce","Me","Co","BM","CoT","Para"))
  else if (roi == "APC")
    results_select <- subset(results_abs,roi %in% c("APc","APn"))
  else if (roi == "PPC")
    results_select <- subset(results_abs,roi=="PPc")
  else
    results_select <- results_abs
  
  # plot
  plots <- list()
  plots_avg <- list()
  odors <- c("car","cit","tra","ind")
  for (odor in odors) {
    for (xlab in c("x","y","z")) {
    p <- paste(xlab,odor,sep = "_")
    # activated only
    indx <- results_select[[paste0("t_",odor,"-lim")]]>params$thr
    plots[[p]] <- ggscatter(results_select[indx,],color = "#4c95c8",
                   x = xlab, y = paste0("m_",odor,"-lim"),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    # averaged
    plots_avg[[p]] <- ggscatter(results_select[indx,lapply(.SD, mean),.SDcol=paste0("m_",odor,"-lim"),by=xlab],color = "#4c95c8",
                   x = xlab, y = paste0("m_",odor,"-lim"),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    }
  }
  print(wrap_plots(plots,ncol = 3,nrow = length(odors)))
  print(wrap_plots(plots_avg,ncol = 3,nrow = length(odors)))
  

  # lim-cit and lim-car
  col <- grep("t_(car|cit)-lim",colnames(results_select))
  # select rows that all columns are above threshold in data.table
  results_select <- results_select[,t:=all(.SD>params$thr),.SDcols = col, by = seq_len(nrow(results_select))]
  # print(ggscatter(results_select[t==TRUE,lapply(.SD, mean),.SDcol=5:14,by=c("x","y","z")],color = "#4c95c8",
  print(ggscatter(results_select[t==TRUE,],color = "#4c95c8",
                   x = paste0("m_","cit-lim"), y = paste0("m_","car-lim"),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
          labs(title = paste(roi,"all",sep = "_"))+
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = ro i)+
        theme_prism(base_line_size = 0.5))
}
```

```{r fig.height=9, fig.width=9}
# Pir and Amy
for (roi in c("Pir","Amy","All")) {
  # pir
  if (roi == "Pir")
    results_select <- subset(results_abs,roi %in% c("APc","PPc","APn"))
  else if (roi == "Amy")
    results_select <- subset(results_abs,roi %in% c("La","Ba","Ce","Me","Co","BM","CoT","Para"))
  else if (roi == "APC")
    results_select <- subset(results_abs,roi %in% c("APc","APn"))
  else if (roi == "PPC")
    results_select <- subset(results_abs,roi=="PPc")
  else
    results_select <- results_abs
  
  # plot
  plots <- list()
  plots_avg <- list()
  odors <- c("car|cit","ind|tra","car|citn","ind|tran")
  results_select[,carcit:=(`m_cit-lim`)-(`m_car-lim`)]
  results_select[,indtra:=(`m_tra-lim`)-(`m_ind-lim`)]
  results_select[,carcitn:=((`m_cit-lim`)-(`m_car-lim`))/((`m_cit-lim`)+(`m_car-lim`))]
  results_select[,indtran:=((`m_tra-lim`)-(`m_ind-lim`))/((`m_tra-lim`)+(`m_ind-lim`))]
  for (odor in odors) {
    # lim-cit and lim-car
    col <- grep(paste0("t_(", substr(odor,1,7), ")-lim"),colnames(results_select))
    # select rows that all columns are above threshold in data.table
    results_select <- results_select[,t:=any(.SD>params$thr),.SDcols = col, by = seq_len(nrow(results_select))]
    
    for (xlab in c("x","y","z")) {
    p <- paste(xlab,odor,sep = "_")
    # activated only
    plots[[p]] <- ggscatter(results_select[t==TRUE,],color = "#4c95c8",
                   x = xlab, y = str_replace(odor,"\\|",""),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    # averaged
    plots_avg[[p]] <- ggscatter(results_select[t==TRUE,lapply(.SD, mean),.SDcol=str_replace(odor,"\\|",""),by=xlab],
                                color = "#4c95c8", x = xlab, y = str_replace(odor,"\\|",""),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    }
  }
  print(wrap_plots(plots,ncol = 3,nrow = length(odors)))
  print(wrap_plots(plots_avg,ncol = 3,nrow = length(odors)))
}
```


