---
title: "Voxel_search"
author: "Fei"
date: "`r Sys.time()`"
output: html_document
params:
    path: "/Volumes/WD_F/gufei/7T_odor"
    sub: "search_rmbase"
    thr: 2.051831
    percent: 1
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = FALSE,tidy=F,fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
library(ggrepel)
library(R.matlab)
library(plyr)
library(dplyr)
library(tidyr)
library(ggprism)
library(patchwork)
library(gridExtra)
library(plotly)
library(shiny)
ggthemr('fresh',layout = "clean")
```

# Functions and parameters
```{r}
####################################################
# function to load txt file
####################################################
extractdata <- function(path,sub,txtname){
  data <- read.table(file.path(path,sub,txtname))
  # add subject name to the first column
  data <- cbind(rep(sub,times=nrow(data)),data)
  return(data)
}
####################################################
# function to calculate activated voxels
####################################################
calcact <- function(results,roilist,threshold){
  c <- 10
  data <- data.frame(matrix(ncol = 3+c*2, nrow = 0))
  
  for (roi_i in names(roilist)) {
  # select ROI
  roi_label <- roilist[[roi_i]]
  results_r <- subset(results,roi %in% roi_label,select = c((6+c):(5+c+c)))
  subs <- subset(results,roi %in% roi_label,select = 1)
  # check if activated
  results_r <- ifelse(abs(results_r)>threshold,1,0)
  act <- cbind(subs,rep(1,times=nrow(subs)),results_r)
  # calculate number and ratio
  number <- aggregate(.~sub, act, sum)
  ratio <- aggregate(.~sub, act, mean)
  # add roi name
  act <- cbind(rep(roi_i,times=nrow(number)),number,ratio[c(3:(2+c))])
  data <- rbind(data,act)
  }
  # change column names
  names(data)[1:3] <- c("roi","sub","all")
  names(data)[c(4:(3+c))] <- str_replace(names(data)[c(4:(3+c))],"t_","c_")
  names(data)[c((4+c):(3+c+c))] <- str_replace(names(data)[c((4+c):(3+c+c))],"t_","r_")
  # change to percentage
  data[c((4+c):(3+c+c))] <- data[c((4+c):(3+c+c))]*100
  data <- reshape2::melt(data,c("sub","roi"))
  return(data)
}
####################################################
# function to calculate mean values
####################################################
calmean <- function(results,roilist, threshold = 0){
  c <- 10
  data <- data.frame(matrix(ncol = 3+c, nrow = 0))
  
  for (roi_i in names(roilist)) {
  # select ROI
  roi_label <- roilist[[roi_i]]
  results_r <- subset(results,roi %in% roi_label,select = c(6:(5+c)))
  subs <- subset(results,roi %in% roi_label,select = 1)
  act <- cbind(subs,results_r)
  # threshold t value
  results_t <- subset(results,roi %in% roi_label,select = c((6+c):(5+c+c)))
  # # remove any acc below chance
  index <- apply(results_t,1,function(x) any(x>threshold) & all(x>0))
  # index <- apply(results_t,1,function(x) any(x>threshold))
  # significant voxels only
  act <- act[index]
  # calculate mean value
  # m <- aggregate(.~sub, act, mean)
  m <- describeBy(act[,-1],list(act$sub),mat=T)
  m <- subset(m,select = c("group1","mean","se"))
  m <- cbind(str_remove(rownames(m),"1"),m)
  # add roi name
  act <- cbind(rep(roi_i,times=nrow(m)),m)
  data <- rbind(data,act)
  }
  # change column names
  names(data)[1:3] <- c("roi","voxels","sub")
  return(data)
}
# odor pairs
odors <- c("lim", "tra", "car", "cit", "ind")
pairs <- apply(combn(odors, 2), 2, function(x) paste(x[1], x[2], sep = "-"))
opair <- pairs[1:4]
# roi labels
roi_name <- c("Amy","BaLa","CeMe","Cortical",'Pir_new','Pir_old','APC_new','APC_old','PPC')
A <- c(1,3,5,6,7,8,9,15)
B <- c(1,3,8,15)
Ce <- c(5,6)
Co <- c(7,9)
Pn <- c(21,22,29)
Po <- c(21,22)
An <- c(21,29)
Ao <- 21
PPC <- 22
roilist <- list(Amy=A,BaLa=B,CeMe=Ce,Cortical=Co,Pir_new=Pn,Pir_old=Po,APC_new=An,APC_old=Ao,PPC=PPC)
roimarker <- c(1,3,5,6,7,8,9,15,21,22,29)
roilabels <- c("La","Ba","Ce","Me","Co","BM","CoT","Para","APc","PPc","APn")
# colors
gf_color <- c("#f0803b", "#55b96f", "#56a2d4", "#ECB556","#777DDD")
```


```{r}
cat(params$sub)
# sub x y z roi 4mean 4t-value
results <- data.frame(matrix(ncol = 1+12, nrow = 0))
# extract group results
results <- rbind(results,extractdata(params$path,"group",paste0("stats_",params$sub,".txt")))
names(results) <- c("sub","x","y","z","roi",paste("m",pairs,sep = "_"),paste("t",pairs,sep = "_"))
results <- as.data.table(results)
# acc = 0 if below chance
temp <- results[,6:dim(results)[2]]
temp[temp<0] <- 0
results[,6:dim(results)[2]] <- temp
```

# Activated voxels
```{r fig.height=5, fig.width=12}
data_act <- calcact(results,roilist,params$thr)
s <- c("all",paste0("c_",opair))
data_act_mean <- describeBy(data_act$value,list(data_act$variable,data_act$roi),mat=T)
data_act_mean <- subset(data_act_mean,select = c(group1,group2,mean,se))
names(data_act_mean) <- c("voxels","roi","mean","se")
data_act_mean <- mutate(data_act_mean,roi = factor(roi,levels=roi_name))
datachosen <- subset(data_act_mean,voxels %in% s)
datachosen <- mutate(datachosen,voxels = factor(voxels,levels=s,labels = c("all",opair)))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Count',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color)+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)

# ratio
s <- c(paste0("r_",opair))
datachosen <- subset(data_act_mean,voxels %in% s)
datachosen <- mutate(datachosen,voxels = factor(voxels,levels=s,labels = opair))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Percentage',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color[2:5])+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)
```

# Mean value
```{r fig.height=5, fig.width=12}
data_mean <- calmean(results,roilist)
s <- c(paste0("m_",opair))
datachosen <- mutate(data_mean,voxels = factor(voxels,levels=s,labels = opair))
datachosen <- mutate(datachosen,roi = factor(roi,levels=roi_name))
datachosen <- subset(datachosen,voxels%in%c("lim-car","lim-cit"))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Mean acc',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color[3:4])+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)

# activated only
data_mean <- calmean(results,roilist,params$thr)
s <- c(paste0("m_",opair))
datachosen <- mutate(data_mean,voxels = factor(voxels,levels=s,labels = opair))
datachosen <- mutate(datachosen,roi = factor(roi,levels=roi_name))
datachosen <- subset(datachosen,voxels%in%c("lim-car","lim-cit"))
# plot
figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=voxels)) + 
  labs(x='ROI',y='Mean acc',fill='voxels')+#设置坐标轴
  geom_bar(position="dodge", stat="identity") +
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values=gf_color[3:4])+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                position=position_dodge(.9))+
  theme_prism(base_line_size = 0.5)
print(figure)
```

```{r fig.height=9, fig.width=9}
# add labels to roi
results[,roi:=factor(roi,levels = sort(unique(results$roi)),labels=roilabels)]
# reverse xy
results$x <- -results$x
results$y <- -results$y
# absolute difference and x
results_abs<- cbind(abs(results[,2]),results[,3:25])
# 3d scatter plot
# lim-cit
p1 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~`m_lim-cit`,size = I(30),symbol = I("square"), 
        hovertemplate = paste('%{x} %{y} %{z}<br>','%{marker.color:.2f}'))
# lim-car
p2 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~`m_lim-car`,size = I(30),symbol = I("square"), 
        hovertemplate = paste('%{x} %{y} %{z}<br>','%{marker.color:.2f}'))
# activated only average voxels in the same coordinate
# lim-cit
p3 <- plot_ly(results_abs[`t_lim-cit`>params$thr,lapply(.SD, mean),.SDcol=5:14,by=c("x","y","z","roi")],
              x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~`m_lim-cit`,size = I(30),symbol = I("square"), 
        hovertemplate = paste('%{x} %{y} %{z}<br>','%{marker.color:.2f}'))
# lim-car
p4 <-plot_ly(results_abs[`t_lim-car`>params$thr,lapply(.SD, mean),.SDcol=5:14,by=c("x","y","z","roi")],
             x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~`m_lim-car`,size = I(30),symbol = I("square"), 
        hovertemplate = paste('%{x} %{y} %{z}<br>','%{marker.color:.2f}'))
# cit-lim-car-lim
p5 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~(`m_lim-cit`-`m_lim-car`),
        size = I(30),symbol = I("square"), 
        hovertemplate = paste('%{x} %{y} %{z}<br>','%{marker.color:.2f}'))%>%colorbar(title = "struc-quality")
# normalized
p6 <- plot_ly(results,x=~x, y=~y, z=~z, split=~roi,type="scatter3d", mode="markers", 
        color=~(`m_lim-cit`-`m_lim-car`)/(`m_lim-cit`+`m_lim-car`),
        colors=colorRampPalette(c("blue", "white", "red"))(20),size = I(30),symbol = I("square"), 
        hovertemplate = paste('%{x} %{y} %{z}<br>','%{marker.color:.2f}'))%>%colorbar(title = "struc-quality-norm")
htmltools::tagList(list(p1, p2, p3, p4, p5, p6))
```

```{r fig.height=9, fig.width=9}
# Pir and Amy
for (roi in c("Pir","Amy","All")) {
  # pir
  if (roi == "Pir")
    results_select <- subset(results_abs,roi %in% c("APc","PPc","APn"))
  else if (roi == "Amy")
    results_select <- subset(results_abs,roi %in% c("La","Ba","Ce","Me","Co","BM","CoT","Para"))
  else if (roi == "APC")
    results_select <- subset(results_abs,roi %in% c("APc","APn"))
  else if (roi == "PPC")
    results_select <- subset(results_abs,roi=="PPc")
  else
    results_select <- results_abs
  
  # plot
  plots <- list()
  plots_avg <- list()
  odors <- c("car","cit","tra","ind")
  for (odor in odors) {
    for (xlab in c("x","y","z")) {
    p <- paste(xlab,odor,sep = "_")
    # activated only
    indx <- results_select[[paste0("t_","lim-",odor)]]>params$thr
    data_corr <- subset(results_select[indx,],select = c(xlab,paste0("m_","lim-",odor))) 
    # select data above 60% percentile of each group by xlab
    data_corr[, c := quantile(get(paste0("m_","lim-",odor)),1-params$percent), by = c(xlab)]
    # group_by function may encounter issues when plyr loaded
    # data_corr %>% group_by(!!sym(xlab))%>% summarize(quant50 = quantile(get(paste0("m_","lim-",odor)),0.5))
    # https://stackoverflow.com/questions/21653295/dplyr-issues-when-using-group-bymultiple-variables
    plots[[p]] <- ggscatter(data_corr[get(paste0("m_","lim-",odor))>=c,],color = "#4c95c8",
                   x = xlab, y = paste0("m_","lim-",odor),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    # averaged
    plots_avg[[p]] <- ggscatter(data_corr[get(paste0("m_","lim-",odor))>=c,lapply(.SD, mean),.SDcol=2,by=xlab],color = "#4c95c8",
                   x = xlab, y = paste0("m_","lim-",odor),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    }
  }
  print(wrap_plots(plots,ncol = 3,nrow = length(odors)))
  print(wrap_plots(plots_avg,ncol = 3,nrow = length(odors)))
  
  method = "all "
  if (method=="any"){
    # rows numbers that started with t_lim
    col <- grep("t_lim",colnames(results_select))
    # select rows that any columns are above threshold in data.table
    results_select <- results_select[,t:=any(.SD>params$thr),.SDcols = col, by = seq_len(nrow(results_select))]
  } else{
    # lim-cit and lim-car
    col <- grep("t_lim-(car|cit)",colnames(results_select))
    # select rows that all columns are above threshold in data.table
    results_select <- results_select[,t:=all(.SD>params$thr),.SDcols = col, by = seq_len(nrow(results_select))]
  }
  # print(ggscatter(results_select[t==TRUE,lapply(.SD, mean),.SDcol=5:14,by=c("x","y","z")],color = "#4c95c8",
  print(ggscatter(results_select[t==TRUE,],color = "#4c95c8",
                   x = paste0("m_","lim-cit"), y = paste0("m_","lim-car"),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
          labs(title = paste(roi,method,sep = "_"))+
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = ro i)+
        theme_prism(base_line_size = 0.5))
}
```

```{r fig.height=9, fig.width=9}
# Pir and Amy
for (roi in c("Pir","Amy","All")) {
  # pir
  if (roi == "Pir")
    results_select <- subset(results_abs,roi %in% c("APc","PPc","APn"))
  else if (roi == "Amy")
    results_select <- subset(results_abs,roi %in% c("La","Ba","Ce","Me","Co","BM","CoT","Para"))
  else if (roi == "APC")
    results_select <- subset(results_abs,roi %in% c("APc","APn"))
  else if (roi == "PPC")
    results_select <- subset(results_abs,roi=="PPc")
  else
    results_select <- results_abs
  
  # plot
  plots <- list()
  plots_avg <- list()
  odors <- c("car|cit","ind|tra","car|citn","ind|tran")
  results_select[,carcit:=(`m_lim-cit`)-(`m_lim-car`)]
  results_select[,indtra:=(`m_lim-tra`)-(`m_lim-ind`)]
  results_select[,carcitn:=((`m_lim-cit`)-(`m_lim-car`))/((`m_lim-cit`)+(`m_lim-car`))]
  results_select[,indtran:=((`m_lim-tra`)-(`m_lim-ind`))/((`m_lim-tra`)+(`m_lim-ind`))]
  for (odor in odors) {
    # lim-cit and lim-car
    col <- grep(paste0("t_lim-(", substr(odor,1,7), ")"),colnames(results_select))
    # select rows that all columns are above threshold in data.table
    results_select <- results_select[,t:=any(.SD>params$thr),.SDcols = col, by = seq_len(nrow(results_select))]
    
    for (xlab in c("x","y","z")) {
    p <- paste(xlab,odor,sep = "_")
    # activated only
    plots[[p]] <- ggscatter(results_select[t==TRUE,],color = "#4c95c8",
                   x = xlab, y = str_replace(odor,"\\|",""),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    # averaged
    plots_avg[[p]] <- ggscatter(results_select[t==TRUE,lapply(.SD, mean),.SDcol=str_replace(odor,"\\|",""),by=xlab],
                                color = "#4c95c8", x = xlab, y = str_replace(odor,"\\|",""),alpha = 0.8,
              conf.int = TRUE,add = "reg.line",add.params = list(color = "gray20"),fullrange = F,
              position=position_jitter(h=0.02,w=0.02, seed = 5)) +
        stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")),
                 show.legend=F)+
        # labs(title = roi)+
        theme_prism(base_line_size = 0.5)
    }
  }
  print(wrap_plots(plots,ncol = 3,nrow = length(odors)))
  print(wrap_plots(plots_avg,ncol = 3,nrow = length(odors)))
}
```