---
title: "PPI"
author: "GuFei"
date: '2020-04-24'
output:
  html_document:
  df_print: paged
---
```{r include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = TRUE)
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
```

# 汇总数据
```{r}

rm(list = ls())
load("All.RData")

# 分组统计
analyze <- describeBy(all[2:6],list(all$position,all$condition,all$roi),mat = TRUE)
# 把vars列中的数字替换为名称
varnames <- row.names(analyze)
tempstr <- strsplit(varnames,"[0-9]")
varnames <- sapply(tempstr,'[',1)
analyze$vars <- as.factor(varnames)

```

# 分析
## 统计voxel的数量
```{r fig.height=4, fig.width=6}
# 画图时的字体大小
WORD_SIZE = 15

voxel <- subset(all, select = c(Sub,Count,position))
#long format data
MANOVA(voxel,subID = 'Sub',dv='Count',within = c("position"))

# 绘图
ggthemr('fresh',layout = "clean")

# 图的标题
title <- 'Voxel Count'
# 提取需要画图的部分
datachosen <- subset(analyze, vars=='Count',select = c(mean,se,vars,group1))
# Error bars represent standard error of the mean
figure <- ggplot(datachosen, aes(x=group1, y=mean)) +
  #coord_cartesian(ylim=c(0,0.4)) +  # 设置y轴坐标范围
  labs(title = title ,x='Position',y='Voxel Count')+#设置坐标轴
  theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
        axis.text.y = element_text(size=WORD_SIZE),
        axis.title.x = element_text(size=WORD_SIZE),
        axis.title.y = element_text(size=WORD_SIZE),
        legend.title = element_text(size=WORD_SIZE),
        legend.text = element_text(size=WORD_SIZE),
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(breaks=waiver(),expand = c(0,0))+
  geom_bar(position="dodge", stat="identity") +
  # scale_fill_manual(values = colors[1:2])+ #颜色
  scale_fill_brewer(palette = "Set2",direction = -1)+ #颜色
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                width=.2,color='black',      # Width of the error bars
                position=position_dodge(.9))
print(figure)

```


## 方差分析和画图

```{r fig.height=8, fig.width=12}
# 颜色
gf_color <- c("#A1D99B","#41AB5D","#9ECAE1","#4292C6","#FDAE6B","#F16913","#BCBDDC","#807DBA")
# 绘图
ggthemr('fresh',layout = "clean")

# 不同位置的杏仁核
for (croi in unique(all$roi)) {
    # figurelist用来保存四个图像
  i=1
  figurelist <- list()
  for (con in unique(all$condition)) {
    string <- sprintf('%s条件下%s的结果',con,croi)
    cat(string)
    # 进行方差分析
    # 选择对应的数据
    data_anova <- subset(all,roi==croi&condition==con,select = c(1:3,7))

    #更改变量名称
    names(data_anova) <- c('Sub','Visibility_I','Visibility_V','position')
    data_anova$position <- paste0('Pos_',data_anova$position)
    #更换数据格式
    data_anova <- reshape2::melt(data_anova,c('Sub','position'))
    data_anova <- reshape2::dcast(data_anova,Sub~position+variable)

    #方差分析
    MANOVA(data_anova,dvs =names(data_anova[-1]),
           dvs.pattern ='Pos_(.*)_Visibility_(.)',
           within=c('Position','Visibility'))

    # t检验，t值看起来不对可能是因为小数位数
    cat(paste0('t检验：',names(data_anova)[2],'---',names(data_anova)[3],'\n'))
    t <- t.test(x= data_anova[,2],
           y= data_anova[,3], paired= TRUE)
    print(t,digits = 8)

    cat(paste0('t检验：',names(data_anova)[4],'---',names(data_anova)[5],'\n'))
    t <- t.test(x= data_anova[,4],
           y= data_anova[,5], paired= TRUE)

    print(t,digits = 8)
    # 方差分析验证t检验
    # MANOVA(data_anova[1:3],dvs =names(data_anova[2:3]),
    #        dvs.pattern ='.*_Visibility_(.)',
    #        within='Visibility')


    cat("\n绘图\n")

    # 图的标题
    title <- paste0(croi,'_',con)
    # 提取需要画图的部分
    datachosen <- subset(analyze,group2==con & group3==croi & vars%in%c('Inv','Vis'),select = c(mean,se,vars,group1))
    # Error bars represent standard error of the mean
    figurelist[[i]] <- ggplot(datachosen, aes(x=group1, y=mean,fill=factor(vars,levels = c("Vis","Inv")))) +
      #coord_cartesian(ylim=c(0,0.4)) +  # 设置y轴坐标范围
      labs(title = title ,x='Position',y='Mean β',fill='Condition')+#设置坐标轴
      theme(axis.text.x = element_text(size=WORD_SIZE),  # 设置x轴字体大小，以下同理
            axis.text.y = element_text(size=WORD_SIZE),
            axis.title.x = element_text(size=WORD_SIZE),
            axis.title.y = element_text(size=WORD_SIZE),
            legend.title = element_text(size=WORD_SIZE),
            legend.text = element_text(size=WORD_SIZE),
            plot.title = element_text(hjust = 0.5)) +
      scale_y_continuous(expand = c(0,0))+
      geom_bar(position="dodge", stat="identity") +
      # scale_fill_manual(values = colors[1:2])+ #颜色
      scale_fill_brewer(palette = "Set2",direction = -1)+ #颜色
      geom_errorbar(aes(ymin=mean-se, ymax=mean+se),
                    width=.2,color='black',      # Width of the error bars
                    position=position_dodge(.9))
    print(figurelist[[i]])
    i <- i+1
  }#四种相减方式的循环结束
    # 合并几个图到一个里面
    ppi <- ggarrange(plotlist = figurelist,nrow = 2,ncol = 2,labels=c("A","B","C","D"))
    print(ppi)
    # 测试保存图片
    # jpeg(file="myplot.jpeg",width = 1920,height = 1080)
    # ggarrange(figure_4,figure_8,ncol = 2,labels=c("A","B"),widths = c(1,2))
    # dev.off()

}
# # 可以查看对应主题的颜色
# colour_plot(swatch())
# colour_plot(ggthemr("pale"))
# colour_plot(ggthemr("greyscale"))
# colour_plot(ggthemr("solarized"))
# # colorbrewer选择颜色，生成颜色
# display.brewer.all()
# colors <- brewer.pal(8,"Set2")
# colour_plot(colors)
# # colors是自带颜色函数
# colors()
```
