---
output: html_document
params:
    path: "/Volumes/WD_F/gufei/3t_cw/"
    roi: !r c('Amy8_at165')
    roiname: !r c("Amy")
    sub: !r c(sprintf('S%02d',c(3:29)))
    suffix: "_tent_16p.txt"
title: "ROIs"
author: "Fei"
date: "`r Sys.time()`"
---

<style>
.html-widget {
    margin: auto;
}
</style>

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = T, message = F, cache = FALSE,tidy=F,fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
library(ggrepel)
library(plotly)
library(R.matlab)
library(plyr)
library(dplyr)
library(tidyr)
library(ggprism)
ggthemr('fresh',layout = "clean")
```

```{r include=FALSE}
# array of odors
odors <- c('FearPleaVis','FearPleaInv','FearUnpleaVis','FearUnpleaInv','HappPleaVis','HappPleaInv','HappUnpleaVis','HappUnpleaInv')
pd <- position_dodge(0)
roi_color <- c("#1F78B4", "#FB9A99", "#FDBF6F", "#A1D99B", "#41AB5D", "#006D2C")
# colors for odors
gf_color <- c("#41AB5D","#A1D99B", "#4292C6","#9ECAE1", "#F16913","#FDAE6B", "#807DBA", "#BCBDDC")
pd <- position_dodge(0.1)
##################################################
# function to extract time courses from txt file
##################################################
extractdata <- function(txtname,odors){
# use comment.char = "" to avoid problems caused by "#"
data <- read.table(txtname,header = TRUE,fill=TRUE,comment.char = "",
                   colClasses = c("character","character","NULL","character"),
                   col.names = c("sub","time","Null","NZmean"))
# 去掉每个被试开头的标题的那一行
data$sub[data$sub=="File"] <- NA
data <- na.omit(data)

# data1 <- data[c(-3)]
sub <- strsplit(data$sub,"\\.")
sub <- sapply(sub,"[",2)
data$sub <- sub
# get roiname
roi <- strsplit(txtname,fixed = T,"/")
roi <- strsplit(sapply(roi,"[",length(roi[[1]])),fixed = T,"_p_tent")
ntime <- as.numeric(str_extract(sapply(roi,"[",2),"[0-9][0-9]"))
roi <- sapply(roi,"[",1)
# repeat times from 0 to 16
times <- seq(0,ntime,2)
data$time <- rep(times,times=length(odors))
data$NZmean <- as.numeric(data$NZmean)
data <- cbind(data,rep(roi,each=nrow(data)))
names(data)[4] <- "roi"
data$odor <- rep(odors,each=length(times))
return(data)
}
```

# Time course

## load data
```{r}
# data_tent stores time courses for each subject and each region
data_tent <- data.frame(sub=0,odor=0,time=0,NZmean=0,roi=0)
data_tent <- data_tent[-1,]
ntime <- as.numeric(str_extract(params$suffix,"[0-9][0-9]"))
for (sub_i in params$sub) {
  # file path
  name <- file.path(params$path,"stats",sub_i,paste0(params$roi,'_p',params$suffix))
  for (region in 1:length(name)) {
  data_tent <- rbind(data_tent,extractdata(name[region],odors))
  }
}
# remove NA
# data_tent <- na.omit(data_tent)
```

## Separate
```{r echo=TRUE}
for (sub_i in params$sub) {
  for (region in params$roi) {
  # choose data
  datachosen <- subset(data_tent,sub==sub_i & roi==region)
  # set time and odor levels
  datachosen$time <- factor(datachosen$time,levels = as.character(seq(0,ntime,2)))
  datachosen$odor <- factor(datachosen$odor,levels = odors)
  # plot time course
  figure_4 <- ggplot(datachosen, aes(x=time, y=NZmean,color=odor,group=odor)) + 
    labs(title = paste(sub_i,region,sep = "_"),
         x='Time(s)',y='Percent of signal change (%)',color='Odor')+#设置坐标轴
    scale_y_continuous(expand = c(0,0))+
    coord_cartesian(ylim=c(min(datachosen$NZmean)-1,max(datachosen$NZmean+1))) + 
    # scale_fill_manual(values = colors[1:2])+ #颜色
    scale_color_manual(values = gf_color)+ #自选颜色
    scale_x_discrete(expand = c(0,0.1))+
    geom_line(position = pd) +
    geom_hline(yintercept=0, linetype="dotted")+
    geom_point(position = pd)
  # print(figure_4)
  pfigure <- figure_4 + theme_prism(base_line_size = 0.5)
  print(pfigure)
}
}
```

## Average sub
```{r}
for (region in c(params$roi,"All")) {
# choose data
  if (region =="All")
    datachosen <- subset(data_tent,roi%in%params$roi[c(1,5)])
  else
    datachosen <- subset(data_tent,roi==region)
  datachosen <- describeBy(datachosen$NZmean,list(datachosen$odor,datachosen$time),mat = T)
  datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
  names(datachosen) <- c("odor","time","mean","se")
  # set time and odor levels
  datachosen$time <- factor(datachosen$time,levels = as.character(seq(0,ntime,2))) 
  datachosen$odor <- factor(datachosen$odor,levels = odors)
  # plot time course
  figure_4 <- ggplot(datachosen, aes(x=time, y=mean,color=odor,group=odor)) + 
    labs(title = paste(region,sep = "_"),
         x='Time(s)',y='Percent of signal change (%)',color='odor')+#设置坐标轴
    scale_y_continuous(expand = c(0,0))+
    # coord_cartesian(ylim=c(min(datachosen$mean)-0.1,max(datachosen$mean+0.1))) + 
    # scale_fill_manual(values = colors[1:2])+ #颜色
    scale_color_manual(values = gf_color)+ #自选颜色
    scale_fill_manual(values = gf_color)+ #自选颜色
    scale_x_discrete(expand = c(0,0.1))+
    geom_line(position = pd) +
    geom_hline(yintercept=0, linetype="dotted")+
    # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
    geom_ribbon(aes(ymin = mean - se, ymax = mean + se, fill = odor), 
                alpha = 0.2,linetype=0)+
    geom_point(position = pd)
  # print(figure_4)
  pfigure <- figure_4 + theme_prism(base_line_size = 0.5)
  print(pfigure)
}
```

## Average sub and odor
```{r}
# store tent for each roi
roi_tent <- data.frame(matrix(ncol = 4, nrow = 0))
for (region in params$roi) {
# choose data
datachosen <- subset(data_tent,roi==region)
# average by odors first so that df for standard error is number of subs
datachosen <- aggregate(datachosen$NZmean, list(datachosen$sub,datachosen$roi,datachosen$time), FUN=mean)
datachosen <- describeBy(datachosen$x,list(datachosen$Group.3),mat = T)
datachosen <- subset(datachosen,select = c(group1,mean,se))
names(datachosen) <- c("time","mean","se")
# set time and odor levels
datachosen$time <- factor(datachosen$time,levels = as.character(seq(0,ntime,2)))

# plot time course
# figure_4 <- ggplot(datachosen, aes(x=time, y=mean,group=1)) +
#   labs(title = paste("All",region,sep = "_"),
#        x='Time(s)',y='Percent of signal change (%)')+#设置坐标轴
#   scale_y_continuous(expand = c(0,0))+
#   coord_cartesian(ylim=c(min(datachosen$mean)-0.2,max(datachosen$mean+0.2)),
#                   clip = 'off') +
#   scale_fill_manual(values = gf_color)+ #颜色
#   scale_color_manual(values = gf_color)+ #自选颜色
#   scale_x_discrete(expand = c(0,0))+
#   geom_line(position = pd) +
#   geom_hline(yintercept=0, linetype="dotted")+
#   geom_ribbon(aes(ymin = mean - se,
#                   ymax = mean + se), alpha = 0.2)+
#   # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
#   geom_point(position = pd)
# # print(figure_4)
# pfigure <- figure_4 + theme_prism(base_line_size = 0.5)
# print(pfigure)

# save datachosen to roi_tent
datachosen <- cbind(datachosen,rep(region,each=nrow(datachosen)))
roi_tent <- rbind(roi_tent,datachosen)
}
# change name
names(roi_tent)[4] <- "roi"
# set levels
roi_tent$roi <- factor(roi_tent$roi,levels = params$roi,labels = params$roiname)

# plot
figure_roi <- ggplot(roi_tent, aes(x=time, y=mean,group=roi,color=roi)) + 
  labs(x='Time(s)',y='Percent of signal change (%)')+#设置坐标轴
  scale_y_continuous(expand = c(0,0))+
  coord_cartesian(ylim=c(min(roi_tent$mean)-0.1,max(roi_tent$mean+0.1)),
                  clip = 'off') + 
  scale_color_manual(values = roi_color)+ #自选颜色
  scale_fill_manual(values = roi_color)+ #自选颜色
  scale_x_discrete(expand = c(0,0))+
  geom_line(position = pd) +
  geom_hline(yintercept=0, linetype="dotted")+
  # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
  geom_ribbon(aes(ymin = mean - se, ymax = mean + se, fill = roi),
              alpha = 0.2,linetype=0)+
  geom_point(position = pd)
# print(figure_4)
pfigure <- figure_roi + theme_prism(base_line_size = 0.5)
print(pfigure)
```
