---
output: html_document
title: "Plots for monkeys"
author: "Fei"
date: "`r Sys.time()`"
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = F,tidy = F,
fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(bruceR)
library(psych)
library(RColorBrewer)
library(ggpubr)
library(ggrepel)
library(R.matlab)
library(ggprism)
library(sysfonts)
library(pheatmap)
library(mlr3verse)
library(rpart.plot)
library(abind)
library(purrr)
font_add("Helvetica", "Helvetica.ttc")
theme_set(theme_prism(base_size = 9,
                      base_family = "Helvetica",
                      base_fontface = "plain",
                      base_line_size = 0.5,
                      base_rect_size = 0.5,))
# theme_update(text = element_text(family = "Helvetica",
#                                  face = "plain", size = 9))
```

# settings and functions
```{r}
# settings
colors <- c(
    "#777DDD", "#69b4d9", "#149ade", "#41AB5D", "#ECB556",
    "#000000", "#E12A3C", "#777DDD", "#41AB5D", "#DE7B14"
)
cmap <- c("#D95319", "#EDB120", "#7E2F8E", "#0072BD")
odors <- c("Ind", "Iso_l", "Iso_h", "Peach", "Banana", "Air", "Odor")
monkeys <- c("RM033", "RM035", "2monkey")
root_dir <- "/Volumes/WD_D/gufei/monkey_data/yuanliu/merge2monkey"
# function to plot tree
tree_plot <- function(model,color_list,title){
    rpart.plot(model,
        type = 1, # left and right split labels (see Figure 2)
        clip.right.labs = FALSE, # full right split labels
        extra = 104, # show nbr of obs and percentages (see Figure 3)
        under = FALSE, # position extra info _under_ the boxes
        tweak = 1, # tweak the text
        fallen.leaves = FALSE, # put leaves at the bottom of plot
        box.palette = color_list, # color of the boxes
        branch = .3, # branch lines with narrow shoulders and down slopes
        round = 0, # no rounding of node corners i.e. use rectangles
        leaf.round = 9, # round leaf nodes (for leaves, this supersedes the round arg)
        main = title, # title
        legend.x = 0,
        legend.y = 1,
        branch.col = "gray", # color of branch lines
        branch.lwd = 2 # line width of branch lines
    ) 
}
# recode odors
recode_odor <- function(power, tar) {
    # remove air
    power_noair <- power[odor != 6, ]
    # convert odor to factors
    power_noair[, odor := factor(odor, levels = as.character(1:5), labels = odors[1:5])]
    # frequency bands
    cutoff <- c(1, 4, 8, 13, 30, 80)
    freqbands_name <- c("delta", "theta", "alpha", "beta", "gamma")
    # dcast to frequencies
    power_by_time <- dcast(power_noair, roi + odor + time ~ freq, value.var = "power")
    for (i in 1:length(freqbands_name)) {
        # find freq index
        col <- which(freq >= cutoff[i] & freq < cutoff[i + 1]) + 3
        # average each frequency band
        power_by_time[, (freqbands_name[i]) := rowMeans(.SD), .SDcols = col]
    }
    # recode
    if (tar == "odor5") {
        power_by_time[, (tar) := odor]
    } else if (tar == "odor4") {
        power_by_time[, (tar) := car::recode(odor, 'c("Iso_l", "Iso_h") = "Iso"')]
        power_by_time[, (tar) := factor(odor4, levels = c("Ind", "Iso", "Peach", "Banana"))]
    } else if (tar == "valence") {
        power_by_time[, (tar) := car::recode(
            odor,'c("Ind", "Iso_l", "Iso_h") = "Neg"; c("Peach", "Banana") = "Pos"')]
        color_list <- color_list_all[c(1, 5)]
    } else if (tar == "intensity") {
        # select iso_l and iso_h
        power_by_time <- power_by_time[odor %in% c("Iso_l", "Iso_h"), ]
        power_by_time[, (tar) := factor(odor, levels = c("Iso_l", "Iso_h"), labels = c("Low", "High"))]
    }
    return(power_by_time)
}
```

# heatmap of monkey's zpower

```{r fig.height=4, fig.width=4}
for (m in monkeys){    
    pic_dir <- file.path(root_dir, 'pic/powerspec',m);
    # read zpower mat file
    data_pow <- readMat(file.path(pic_dir,'zpower_7s_1_80hz.mat'))
    # roi-odor condition-frequency bands
    zpower <- unlist(data_pow$zpower)
    rois <- unlist(data_pow$rois)
    freqbands <- paste0(c("1-4","4-8","8-13","13-30","30-50","50-80","30-80"),"Hz")
    # heatmap settings
    condition <- c(1:5)
    rownames(zpower) <- rois
    colnames(zpower) <- odors
    # color scale
    b <- seq(-0.1,0.1,length.out = 100)
    # plot heatmap and dendrogram for each frequency band
    for(freq in c(1:7)){
        pheatmap(zpower[, condition, freq],
        clustering_distance_rows = "correlation",
        clustering_distance_cols = "correlation",
        cellwidth = 15,cellheight = 15,breaks = b,
        color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdBu")))(100),
        main = freqbands[freq],
        filename = file.path(pic_dir,paste0('heatmap_',freqbands[freq],'.pdf')))
    }
}
```

# load and store power data
```{r}
power_data <- list()
# for each monkey
for (m in monkeys) {  
    # use power for each frequency band
    av_freq  <- TRUE
    # split test data set
    test <- FALSE    
    # colors for tree plot
    color_list_all <- list()
    c <- colors[1:5]
    c[2] <- "#858585"
    for (i in 1:5) {
        color_list_all[[i]] <- colorRampPalette(c("white", c[i]))(10)
    }
    # pic_dir
    pic_dir <- file.path(root_dir, "pic/pca_power/noair", m)
    # read zpower mat file
    data_pca <- readMat(file.path(pic_dir, "data_pca.mat"))
    # reorganize data from matlab cell to R
    roi_num  <- length(data_pca[[1]])/3
    rois <- unlist(data_pca[[1]][1:roi_num])
    # along 0 will bind in new dimension
    power <- abind(map(data_pca[[1]][(roi_num * 1 + 1):(roi_num * 2)], 1), along = 0)
    
    # bind list along the 3rd dimension
    # power <- abind(do.call(c, data_pca[[1]][(roi_num * 1 + 1):(roi_num * 2)]), along = 1)
    # power <- abind(map(data_pca[[1]][(roi_num * 1 + 1):(roi_num * 2)],1), along = 4)
    # labels <- abind(map(data_pca[[1]][(roi_num * 2 + 1):(roi_num * 3)],1),along = 0)

    # frequency
    freq <- 10^(seq(log10(1), log10(200), length.out = 51))
    freqnames <- sprintf("freq_%02d", c(1:dim(power)[4]))
    cutoff <- c(1, 4, 8, 13, 30, 80)
    freqbands_name <- c("delta", "theta", "alpha", "beta", "gamma")
    odor_num <- dim(power)[2]
    # set dimnames
    dimnames(power) <- list(c(1:roi_num), c(1:odor_num), seq(0, 3, 0.05), freqnames)
    # convert to data.table
    power <- as.data.table(power)
    names(power) <- c("roi", "odor", "time", "freq", "power")
    # convert roi and time to factors
    power[, time := factor(time, levels = as.character(seq(0, 3, 0.05)))]
    power[, roi := factor(roi, levels = as.character(1:roi_num), labels = rois)]
    # convert time and freq to numeric
    # power[,(c(3:4)):=lapply(.SD,as.numeric),.SDcols=c(3:4)]
    # store to list
    power_data[[m]] <- power
}
```

# decision tree based on time-frequency analysis

```{r, fig.height=4, fig.width=4}
# for each monkey
for (m in monkeys) {
    # set random seed
    set.seed(4869)   
    # load power data
    power <- power_data[[m]]    
    # for each coding methods
    tars <- c("odor5","odor4","valence","intensity")
    # store results
    datalist <- list()
    for (tar in tars){
        # recode targets
        power_by_time <- recode_odor(power, tar)
        if (tar=="odor5"){
            color_list <- color_list_all
        } else if (tar == "odor4"){
            color_list <- color_list_all[-2]
        } else if (tar == "valence"){
            color_list <- color_list_all[c(1,5)]
        } else if (tar == "intensity"){
            color_list <- color_list_all[c(2,3)]
        }
        # model by mlr3, select fearures
        task <- as_task_classif(power_by_time, target = tar)
        if (av_freq){
            task_freq <- task$clone()$select(freqbands_name)    
        } else {
            task_freq <- task$clone()$select(freqnames)
        }    
        # rpart classifier
        learner <- lrn("classif.rpart")
        measure = msr("classif.acc")
        # whether to test on test set
        if (test){
            split <- partition(task_freq, ratio = 55/61)
            train_idx <- split$train
            test_idx <- split$test
            learner$train(task_freq, row_ids = train_idx)
            prediction = learner$predict(task_freq, row_ids = test_idx)
            acc_test <- prediction$score(measure)
        } else {
            train_idx <- c(1:task_freq$nrow)
            learner$train(task_freq) 
            acc_test <- 0    
        }
        # test performance
        train_pre = learner$predict(task_freq, row_ids = train_idx)
        acc_train <- train_pre$score(measure)
        print(c(m, acc_train, acc_test))

        # get responses
        # select <- c("roi", "time", tar)
        # results <- cbind(power_by_time[,..select],train_pre$response)
        results <- cbind(power_by_time[, .SD, .SDcols = c("roi", "time", tar)], train_pre$response)
        setnames(results,3:4,c("true","response"))
        # add a column indicating target
        results[,`:=`(target = tar)]
        # calculate accuracy
        results <- results[,acc:=ifelse(true==response,1,0)]
        # save to list
        datalist[[tar]] <- results
        # average by odor and roi
        mean_acc <- results[target == tar, .(acc = mean(acc)), by = c("roi", "time")]
        # plot result matrix
        ggplot(mean_acc, aes(x = time, y = roi, fill = acc)) +
            geom_tile() + coord_equal(0.618*61/roi_num) +
            scale_fill_distiller(palette = "Greens",direction = 1,
            limits=c(0,1),breaks=seq(0,1,0.2)) +
            labs(title = paste(m, tar, sprintf("%.2f%%",100*acc_train), sep = "_")) +
            scale_x_discrete(breaks = seq(0,3,0.5))
        ggsave(file.path(pic_dir, paste0("Acc_", tar, ".pdf")), width = 5, height = 3)
        # save tree plot        
        # svg(file.path(pic_dir, "decision_tree.svg"))
        pdf(file.path(pic_dir, paste0("decision_tree_", tar, ".pdf")))
        title <- paste(m, tar, sprintf("%.2f%%", 100 * acc_train), sep = "_")
        tree_plot(learner$model,color_list,title)
        dev.off()
    }
    # bind all results
    results <- rbindlist(datalist)
    # convert target to factor
    results[, target := factor(results$target, levels = tars)]    
    # plot averaged results
    # average by time
    mean_acc_time <- results[, .(acc = mean(acc)), by = c("target","time")]
    ggplot(mean_acc_time, aes(x = time, y = acc, group = target,color = target)) +
        geom_line() +
        labs(title = paste(m, sep = "_")) +
        scale_color_manual(values = cmap) +
        scale_x_discrete(expand = c(0, 0), breaks = seq(0, 3, 0.5)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1))
    ggsave(file.path(pic_dir, paste0("Acc_time", ".pdf")), width = 4, height = 2.5)
    # average by roi
    mean_acc_roi <- results[, .(acc = mean(acc)), by = c("target","roi")]
    # line plot
    ggplot(mean_acc_roi, aes(x = roi, y = acc, group = target,color = target)) +
        geom_line() +
        labs(title = paste(m, sep = "_")) +
        scale_color_manual(values = cmap) +
        scale_x_discrete(expand = c(0, 0)) +
        scale_y_continuous(expand = c(0, 0), limits = c(0, 1))
    ggsave(file.path(pic_dir, paste0("Acc_roi", ".pdf")), width = 5, height = 2.5)
}
```

# plot distance results

```{r}
dis_data <- list()
# for each monkey
for (m in monkeys) {  
    # pic_dir
    pic_dir <- file.path(root_dir, "pic/pca_power/noair", m)
    # read zpower mat file
    data_pca <- readMat(file.path(pic_dir, "distance_by_time.mat"))
    # reorganize data from matlab cell to R
    rois <- unlist(data_pca$rois)
    roi_num  <- length(rois)
    # along 0 will bind in new dimension
    distance <- abind(map(data_pca$dis.time, 1), along = 0)
    # set dimnames
    dimnames(distance) <- list(c(1:roi_num), seq(0, 3, 0.05), tars)
    # convert to data.table
    distance <- as.data.table(distance)
    setnames(distance,c("roi", "time", "target","dis"))
    # convert roi and time and target to factors
    distance[, time := factor(time, levels = as.character(seq(0, 3, 0.05)))]
    distance[, roi := factor(roi, levels = as.character(1:roi_num), labels = rois)]
    distance[, target := factor(target, levels = tars)]
    # store to list
    dis_data[[m]] <- distance

    # plot distance
    for (tar in tars){
        # average by odor and roi
        mean_dis <- distance[target == tar, .(dis = mean(dis)), by = c("roi", "time")]
        # plot result matrix
        ggplot(mean_dis, aes(x = time, y = roi, fill = dis)) +
            geom_tile() +
            coord_equal(0.618 * 61 / roi_num) +
            scale_fill_distiller(palette = "Greens", direction = 1) +
            labs(title = paste(m, tar,"distance", sep = "_")) +
            scale_x_discrete(breaks = seq(0, 3, 0.5))
        ggsave(file.path(pic_dir, paste0("Dis_", tar, ".pdf")), width = 5, height = 3)
    }
    # average by time
    mean_dis_time <- distance[, .(dis = mean(dis)), by = c("target", "time")]
    ggplot(mean_dis_time, aes(x = time, y = dis, group = target, color = target)) +
        geom_line() +
        labs(title = paste(m, sep = "_")) +
        scale_color_manual(values = cmap) +
        scale_x_discrete(expand = c(0, 0), breaks = seq(0, 3, 0.5)) +
        scale_y_continuous(expand = c(0, 0))
    ggsave(file.path(pic_dir, paste0("Dis_time", ".pdf")), width = 4, height = 2.5)
    # average by roi
    mean_dis_roi <- distance[, .(dis = mean(dis)), by = c("target", "roi")]
    # line plot
    ggplot(mean_dis_roi, aes(x = roi, y = dis, group = target, color = target)) +
        geom_line() +
        labs(title = paste(m, sep = "_")) +
        scale_color_manual(values = cmap) +
        scale_x_discrete(expand = c(0, 0)) +
        scale_y_continuous(expand = c(0, 0))
    ggsave(file.path(pic_dir, paste0("Dis_roi", ".pdf")), width = 5, height = 2.5)
}
```

