---
output: html_document
params:
    path: "/Volumes/WD_F/gufei/blind/"
    sub: !r c(sprintf('S%02d', c(2:4,6:13)))
    analysis: "pade"
    mvpa_pattern: "roi_odor_shift6"
    roi: !r c('Amy8_align','Pir_new','Pir_old','APC_new','APC_old','PPC','EarlyV','V1','V2','V3')
    roiname: !r c("Amy","Pir_new","Pir_old","APC_new","APC_old","PPC","EarlyV","V1","V2","V3")
    set_title: "Decoding_mean"
title: "`r params$set_title`"
author: "Fei"
date: "`r Sys.time()`"
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = FALSE,tidy=F,fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
library(ggrepel)
library(plotly)
library(R.matlab)
library(dplyr)
library(tidyr)
library(ggprism)
# ggthemr('fresh',layout = "clean")
sysfonts::font_add("Helvetica", "Helvetica.ttc")
theme_set(theme_prism(base_size = 9,
                      base_family = "Helvetica",
                      base_fontface = "plain",
                      base_line_size = 0.5,
                      base_rect_size = 0.5,))
gf_color <- c("#412d21", "#777DDD", "#cf7ced", "#ECB556", "#dc0922", "#4292C6", "#e45869", "#41AB5D")
odors <- c("gas","ind","ros","pin","app","min","fru","flo")
```

```{r, include=FALSE}
# function for loading mvpa labels (true and predicted)
readlabel <- function(path,sub,analysis,mvpa_pattern,roi_order) {
  data <- list()
  # 3 kinds of phy
  for (ana in analysis) {
    workingdir <- paste0(path,sub,'/',sub,'.',ana,'.results/mvpa')
    # mvpa <- c("roi","roi_IM","searchligt")
    mvpa <- dir(path=workingdir,pattern = mvpa_pattern)
    # 2 kinds of beta (run and trial)
    for (m in mvpa){
      # dirname start not with 8
      odor2 <- dir(path=file.path(workingdir,m),pattern = "^[^8]")
      odor2 <- subset(odor2,odor2%in%roi_order)
      # 4 kinds of roi
      for (r in odor2){
        # read mat file
        true <- readMat(file.path(workingdir,m,paste0("8odors_",r),'res_true_labels.mat'))
        predict <- readMat(file.path(workingdir,m,paste0("8odors_",r),'res_predicted_labels.mat'))
        true <- unlist(true$results[[9]][[1]][[1]])
        predict <- unlist(predict$results[[9]][[1]])
        labels <- rbind(true,predict)
        
        # add to list
        data <- c(data,list(labels))
        names(data)[length(data)] <- paste(ana,m,r,sep = '_')
        for (campare in dir(path=file.path(workingdir,m,r),pattern = "2")) {
          # read mat file
          true <- readMat(file.path(workingdir,m,r,campare,'res_true_labels.mat'))
          predict <- readMat(file.path(workingdir,m,r,campare,'res_predicted_labels.mat'))
          true <- unlist(true$results[[9]][[1]][[1]])
          predict <- unlist(predict$results[[9]][[1]])
          labels <- rbind(true,predict)
          
          # add to list
          data <- c(data,list(labels))
          names(data)[length(data)] <- paste(ana,m,r,campare,sep = '_')
        }
      }
    }
  }
  return(data)
}


```

# Accuracy_align

```{r echo=FALSE}
path <- params$path
sub <- params$sub
analysis <- params$analysis
mvpa_pattern <- params$mvpa_pattern
roi <- params$roi
roiname <- params$roiname
cat(sub)
```

## align labels
```{r echo=FALSE, fig.height=3, fig.width=4}
mvpa <- mvpa_pattern
run_num <- 6
pairs <- apply(combn(odors,2), 2, function(x) paste(x[1],x[2],sep = "_"))
campares <- paste("2odors",pairs,sep = "_")
acc_run <- data.frame(sub=0,phy=0,beta=0,roi=0,odor=0,acc=0,run=0)
acc_run <- acc_run[-1,]
matrix_all <- data.frame(matrix(ncol = 4, nrow = 0))

compute_acc <- function(labels){
  acc_matrix <- as.matrix(table(odor=labels[1,],prediction=labels[2,]))
  n = sum(acc_matrix)
  acc = 100*sum(diag(acc_matrix))/n # overall accuracy
}

for (sub_i in sub) {
  data_labels <- readlabel(path,sub_i,analysis,mvpa_pattern,roi)
  for (ana in analysis) {
    for (m in mvpa) {
      for (r in roi) {
        # 8odors
        cname <- paste(ana,m,r,sep = '_')
        current_data <- data_labels[[cname]]
        # make sure every class is presented in predict
        current_data_add <- cbind(current_data,matrix(rep(unique(current_data["true",]),each=2),nrow = 2))
        cmatrix <- as.matrix(table(odor=current_data_add["true",],prediction=current_data_add["predict",]))
        cmatrix <- cmatrix-diag(8)
        
        # useful information
        n = sum(cmatrix) # number of instances
        nc = nrow(cmatrix) # number of classes
        truesums = as.numeric(apply(cmatrix, 1, sum)) # number of instances per class
        predsums = as.numeric(apply(cmatrix, 2, sum)) # number of predictions per class
        
        # accuracy
        acc = 100*sum(diag(cmatrix))/n # overall accuracy
        acc_run[nrow(acc_run)+1,] <- c(sub_i,ana,m,r,paste0("8odors_",r),acc,"run_all")
        sep_cmatrix <- split(current_data,rep(1:run_num, each = 2*n/run_num))
        for (i_run in 1:run_num) {
          run_matrix <- matrix(sep_cmatrix[[i_run]],nrow = 2)
          acc = compute_acc(run_matrix) # overall accuracy
          acc_run[nrow(acc_run)+1,] <- c(sub_i,ana,m,r,paste0("8odors_",r),acc,paste("run_",i_run))
        }
        
        # confusion matrix
        cmatrix <- as.data.frame.matrix(cmatrix/truesums)
        cmatrix <- cbind(cmatrix,odors)
        names(cmatrix) <- c(paste0('p_',odors),"odor")
        cmatrix <- gather(cmatrix, prediction, value, p_gas:p_flo)
        cmatrix <- cbind(rep(sub_i,times=nrow(cmatrix)),
                         rep(ana,times=nrow(cmatrix)),
                         rep(m,times=nrow(cmatrix)),
                         rep(r,times=nrow(cmatrix)),
                         cmatrix)
        matrix_all <- rbind(matrix_all,cmatrix)
        
        # 2odors
        for (campare in campares) {
          cname <- paste(ana,m,r,campare,sep = '_')
          current_data <- data_labels[[cname]]
          acc <-  compute_acc(current_data) # overall accuracy
          acc_run[nrow(acc_run)+1,] <- c(sub_i,ana,m,r,campare,acc,"run_all")
          # n*2/nc/run_num pair(true-predict), so should multiply 2 again
          sep_cmatrix <- split(current_data,rep(1:run_num, each = n*2*2/nc/run_num))
          for (i_run in 1:run_num) {
            run_matrix <- matrix(sep_cmatrix[[i_run]],nrow = 2)
            acc  <-  compute_acc(run_matrix) # overall accuracy
            acc_run[nrow(acc_run)+1,] <- c(sub_i,ana,m,r,campare,acc,paste("run_",i_run))
          }
        }
      }
    }
  }
}
acc_run$acc <- as.numeric(acc_run$acc)
acc_run$roi <- factor(acc_run$roi,levels = roi)
acc_run$phy <- factor(acc_run$phy,levels = analysis)
cmatrix <- mutate(cmatrix,odor = factor(odor,rev(odors)), # alphabetical order by default
                  prediction = factor(prediction, levels = paste0('p_',odors))) # force reverse alphabetical order
names(matrix_all)[1:4] <- c("sub","phy","beta","roi")
```

### accuracy all runs 4 odors
```{r echo=FALSE, fig.height=5, fig.width=12}
acc4odor <- subset(acc_run,run=="run_all"&odor%in%unique(acc_run$odor)[grepl("^8",unique(acc_run$odor))])
  for (m in mvpa_pattern){
    acc4odor <- subset(acc4odor,beta==m)
    datachosen <- describeBy(acc4odor$acc,list(acc4odor$phy,acc4odor$roi),mat=T)
    datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
    names(datachosen) <- c("phy","roi","mean","se")
    datachosen <- mutate(datachosen,roi = factor(roi,levels=params$roi))
    datachosen <- mutate(datachosen,phy = factor(phy,levels=analysis))
    # Bar plot of mean +/-se
    control <- subset(acc4odor,roi == params$roi[1])
    control$acc <- 12.5
    control$roi <- "control"
    acc4odor <- rbind(acc4odor,control)
    acc4odor <- mutate(acc4odor,roi = factor(roi,levels=c(params$roi,"control")))
    figure <- ggbarplot(acc4odor, x = "roi", y = "acc", fill = 'phy', add = "mean_se")+
      labs(title = m ,x='ROI',y='ACC',fill='PHY')+#设置坐标轴
      stat_compare_means(method = "t.test",
                         ref.group = "control",
                         paired = TRUE,
                         label = "p.format")+
      coord_cartesian(ylim=c(0,50)) +
      geom_hline(yintercept=c(control$acc), linetype="dotted")+
      scale_y_continuous(breaks = scales::breaks_width(5),
                         expand = c(0,0))+
      scale_x_discrete(labels=c(roiname,"control"))+
      scale_fill_brewer(palette = "Paired",direction = 1)+ #颜色
      theme_prism(base_line_size = 0.5)
    print(figure)
    # plot individual data
    plotly_fig <- ggplotly(ggplot(acc4odor, aes(x = roi, y = acc,color = sub))
             +geom_point()+color_palette(rainbow(length(sub))),
             tooltip = c("sub","acc"))
  }
plotly_fig
```

### accuracy for each run 4 odors
```{r echo=FALSE, fig.height=3, fig.width=5}
acc4odor_run <- subset(acc_run,run!="run_all"&odor%in%unique(acc_run$odor)[grepl("^8",unique(acc_run$odor))])
  for (m in mvpa_pattern){
    acc4odor_run <- subset(acc4odor_run, beta==m)
    for (r in roi) {
    acc4odor_run_r <- subset(acc4odor_run, roi==r)
    datachosen <- describeBy(acc4odor_run_r$acc,list(acc4odor_run_r$phy,acc4odor_run_r$run),mat=T)
    datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
    names(datachosen) <- c("phy","run","mean","se")
    datachosen <- mutate(datachosen,run = factor(run,levels=paste("run_",1:run_num)))
    datachosen <- mutate(datachosen,phy = factor(phy,levels=analysis))
    # plot
    figure <- ggplot(datachosen, aes(x=run, y=mean, group=phy, color=phy)) + 
      labs(title = paste0(r) ,x='Run',y='ACC',group='PHY')+#设置坐标轴
      geom_line() +
      geom_point()+
      coord_cartesian(ylim=c(0,80),clip = 'off') +
      scale_x_discrete(labels=as.character(1:run_num),expand = c(0,0))+
      scale_y_continuous(breaks=waiver(),expand = c(0,0))+
      scale_color_brewer(palette = "Paired",direction = 1)+ #颜色
      scale_fill_brewer(palette = "Paired",direction = 1)+ #颜色
      geom_ribbon(aes(ymin = mean - se,
                  ymax = mean + se,fill = phy), alpha = 0.1,linetype=0)+
      geom_hline(yintercept=c(control$acc), linetype="dotted")+
      theme_prism(base_line_size = 0.5)
    print(figure)
    }
  }
```


### accuracy all runs 2 odors
```{r echo=FALSE, fig.height=15, fig.width=10}
acc2odor <- subset(acc_run,run=="run_all"&odor%in%unique(acc_run$odor)[grepl("^2",unique(acc_run$odor))])
pairs <- apply(combn(odors,2), 2, function(x) paste(x[1],x[2],sep = "_"))
for (ana in analysis) {
  for (m in mvpa_pattern){
    # plot a matrix
      cmatrix <- subset(acc2odor, phy==ana & beta==m,select = c("sub","roi","odor","acc"))
      # calculate mean values and p values (error when all conditions are 50%: data are essentially constant)
      p <- aggregate(cmatrix$acc, list(cmatrix$odor,cmatrix$roi), FUN= function(x) {t.test(x,mu=50)$p.value})
      cmatrix <- cbind(aggregate(cmatrix$acc, list(cmatrix$odor,cmatrix$roi), mean),p[,3])
      names(cmatrix) <- c("odor","roi","acc","p")
      cmatrix$plabels <- cut(cmatrix$p, breaks=c(-Inf, 0.001, 0.01, 0.05, 0.10, Inf), 
                           label=c("***", "**", "*", "†", ""))
      cmatrix[,3] <- round(cmatrix[,3],digits = 2)
      cmatrix <- mutate(cmatrix,odor = factor(odor,levels = paste0('2odors_',pairs),labels = pairs),
                        roi = factor(roi, levels = params$roi, labels = params$roiname)) # force reverse alphabetical order
      # test <- aggregate(matrix_all$value, list(matrix_all$odor,matrix_all$prediction), mean)
      figure <- ggplot(cmatrix, aes(x=roi, y=odor, fill=acc)) +
        geom_tile() + theme_bw() + coord_equal() +
        scale_fill_distiller(palette="Greens", direction=1,limits=c(50, 80) ) +
        labs(title = paste(ana,m,sep = "_")) + # using a title instead
        guides(size="none") + # removing legend for `fill`
        geom_text(aes(label=acc), size=4,vjust=0.5, color="black")+ # printing values
        geom_text(aes(label=plabels,size=5,vjust=-0.5), color="black") # printing values
      print(figure)
  }
}
```


```{r echo=FALSE, fig.height=5, fig.width=12}
# plot each odor pair
  for (m in mvpa_pattern){
    acc2odor <- subset(acc2odor, beta==m)
    odor2 <- unique(acc2odor$odor)
    # 建立一个list保存plotyly的结果
    plotly_plots <- htmltools::tagList()
    # 4 kinds of roi
    # for (r in odor2){
    #   acc2odor_r <- subset(acc2odor,odor==r)
    #   datachosen <- describeBy(acc2odor_r$acc,list(acc2odor_r$phy,acc2odor_r$roi),mat=T)
    #   datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
    #   names(datachosen) <- c("phy","roi","mean","se")
    #   datachosen <- mutate(datachosen,roi = factor(roi,levels=params$roi))
    #   datachosen <- mutate(datachosen,phy = factor(phy,levels=analysis))
    #   # Bar plot of mean +/-se
    #   control <- subset(acc2odor_r,roi == params$roi[1])
    #   control$acc <- 50
    #   control$roi <- "control"
    #   acc2odor_r <- rbind(acc2odor_r,control)
    #   acc2odor_r <- mutate(acc2odor_r,roi = factor(roi,levels=c(params$roi,"control")))
    #   figure <- ggbarplot(acc2odor_r, x = "roi", y = "acc", fill = 'phy', add = "mean_se")+
    #     labs(title = paste(m,r,sep = "_") ,x='ROI',y='ACC',fill='PHY')+#设置坐标轴
    #     stat_compare_means(method = "t.test",
    #                        paired = TRUE,
    #                        ref.group = "control",
    #                        label = "p.format")+
    #     coord_cartesian(ylim=c(0,100)) +
    #     scale_y_continuous(breaks = scales::breaks_width(5),
    #                        expand = c(0,0))+
    #     scale_x_discrete(labels=c(roiname,"chance"))+
    #     geom_hline(yintercept=c(50), linetype="dotted")+
    #                  scale_fill_brewer(palette = "Paired",direction = 1)+ #颜色
    #                  theme_prism(base_line_size = 0.5)
    #   print(figure)
    #   # plot individual data
    #   plotly_plots[[r]] <- ggplotly(ggplot(acc2odor_r, aes(x = roi, y = acc,color = sub))+
    #              labs(title = paste(m,r,sep = "_"))+
    #              geom_point()+color_palette(rainbow(length(sub))),
    #            tooltip = c("sub","acc"))
    # }
    
    # interested comparison
    for (ana in analysis) {
      r <- paste0("2odors_",c("fru_flo","ros_pin","ind_pin","gas_ros"))
      acc2odor_r <- subset(acc2odor,phy == ana & odor %in% r)
      datachosen <- describeBy(acc2odor_r$acc,list(acc2odor_r$odor,acc2odor_r$roi),mat=T)
      datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
      names(datachosen) <- c("odor","roi","mean","se")
      datachosen <- mutate(datachosen,roi = factor(roi,levels=params$roi))
      datachosen <- mutate(datachosen,odor = factor(odor,levels=r,
                                                    labels = c("fru_flo","ros_pin","ind_pin","gas_ros")))
      # plot
      figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=odor)) + 
        labs(title = paste(m,ana,sep = "_") ,x='ROI',y='ACC',fill='Odor')+#设置坐标轴
        geom_bar(position="dodge", stat="identity") +
        coord_cartesian(ylim=c(0,100)) +
        scale_y_continuous(breaks=scales::breaks_width(10),expand = c(0,0))+
        scale_x_discrete(labels=roiname)+
        geom_hline(yintercept=c(50), linetype="dotted")+
        scale_fill_brewer(palette = "Paired")+ #颜色
        geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                      position=position_dodge(.9))+
        theme_prism(base_line_size = 0.5)
      print(figure)
      
      # average odor conditions for each subject
      acc2odor_r <- subset(acc2odor,phy == ana)
      # a list for new variable name and conditions to be averaged
      newvar <- list("fruflo_val"=c("gas_fru","gas_flo","gas_ros","gas_pin","gas_app","gas_min",
                                    "ind_ros","ind_pin","ind_app","ind_min","ind_fru","ind_flo"),
                     "valence"=c("gas_ros","gas_pin","gas_app","gas_min","ind_ros","ind_pin","ind_app","ind_min"),
                     "fruflo_b"=c("fru_flo","ros_fru","min_fru","pin_flo","app_flo",
                                  "ros_pin","ros_app","pin_min","app_min"),
                     "between"=c("ros_pin","ros_app","pin_min","app_min"),
                     "fruflo_w"=c("pin_fru","app_fru","ros_flo","min_flo","pin_app","pros_min"),
                     "within"=c("pin_app","ros_min"),"fruflo"=c("fru_flo"),"all"=pairs)
      # subset newvar valence between within
      newvar <- newvar[c("valence","between","within")]
      concolor <- brewer.pal(10, "Paired")
      # agerage conditoins to new dataframe datachosen
      datachosen <- data.frame(matrix(ncol = 4, nrow = 0))
      for (v in names(newvar)){
        # average acc in conditions according to newvar for each subject
        datachosen <- rbind(datachosen,acc2odor_r %>%
            filter(odor %in% paste0("2odors_",newvar[[v]])) %>%
            group_by(sub,roi) %>% 
            dplyr::summarise(acc = mean(acc), .groups = "drop") %>%
            mutate(odor = v))
      }
      # describe
      datachosen <- describeBy(datachosen$acc,list(datachosen$odor,datachosen$roi),mat=T)
      datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
      names(datachosen) <- c("odor","roi","mean","se")
      datachosen <- mutate(datachosen,roi = factor(roi,levels=params$roi))
      datachosen <- mutate(datachosen,odor = factor(odor,levels=names(newvar),
                                                    labels = names(newvar)))
      # plot
      figure <- ggplot(datachosen, aes(x=roi, y=mean, fill=odor)) + 
        labs(title = paste(m,ana,sep = "_") ,x='ROI',y='ACC',fill='Odor')+#设置坐标轴
        geom_bar(position="dodge", stat="identity") +
        coord_cartesian(ylim=c(0,100)) +
        scale_y_continuous(breaks=scales::breaks_width(10),expand = c(0,0))+
        scale_x_discrete(labels=roiname)+
        geom_hline(yintercept=c(50), linetype="dotted")+
        # scale_fill_brewer(palette = "Paired")+ #颜色
        scale_fill_manual(values = concolor[c(2,4,8)])+
        geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                      position=position_dodge(.9))+
        theme_prism(base_line_size = 0.5)
      print(figure)
    }
  }
# plotly_plots
```

### accuracy for each run 2 odors
```{r eval=FALSE, fig.height=3, fig.width=5, include=FALSE}
acc2odor_run <- subset(acc_run,run!="run_all"&odor%in%unique(acc_run$odor)[grepl("^2",unique(acc_run$odor))])
  for (m in mvpa_pattern){
    acc2odor_run <- subset(acc2odor_run, beta==m)
    for (r in roi) {
      odor2 <- unique(acc2odor_run$odor)
      # 4 kinds of roi
      for (o in odor2){
        acc2odor_run_r <- subset(acc2odor_run, roi==r & odor==o)
        datachosen <- describeBy(acc2odor_run_r$acc,list(acc2odor_run_r$phy,acc2odor_run_r$run),mat=T)
        datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
        names(datachosen) <- c("phy","run","mean","se")
        datachosen <- mutate(datachosen,run = factor(run,levels=paste("run_",1:run_num)))
        datachosen <- mutate(datachosen,phy = factor(phy,levels=analysis))

        # plot
        figure <- ggplot(datachosen, aes(x=run, y=mean, group=phy, color=phy)) + 
          labs(title = paste(r,o,sep = '_') ,x='Run',y='ACC',group='PHY')+#设置坐标轴
          geom_line() +
          geom_point()+
          coord_cartesian(ylim=c(0,100),clip = 'off') +
          scale_x_discrete(labels=as.character(1:run_num),expand = c(0,0))+
          scale_y_continuous(breaks=waiver(),expand = c(0,0))+
          scale_color_brewer(palette = "Paired",direction = 1)+ #颜色
          scale_fill_brewer(palette = "Paired",direction = 1)+ #颜色
          geom_ribbon(aes(ymin = mean - se,
                      ymax = mean + se,fill = phy), alpha = 0.1,linetype=0)+
          # scale_color_manual(values = google)+ #颜色
          geom_hline(yintercept=c(50), linetype="dotted")+
          theme_prism(base_line_size = 0.5)
        print(figure)
      }
    }
  }
```

### confusion matrices
```{r fig.height=5, fig.width=6}
for (ana in analysis) {
  for (m in mvpa) {
    for (r in roi) {
      cmatrix <- subset(matrix_all, phy==ana & beta==m & roi==r)
      # calculate mean values
      cmatrix <- aggregate(cmatrix$value, list(cmatrix$odor,cmatrix$prediction), mean)
      names(cmatrix) <- c("odor","prediction","value")
      cmatrix[,3] <- round(100*cmatrix[,3],digits = 2)
      cmatrix <- mutate(cmatrix,odor = factor(odor,rev(odors)), # alphabetical order by default
                        prediction = factor(prediction, levels = paste0('p_',odors))) # force reverse alphabetical order
      # test <- aggregate(matrix_all$value, list(matrix_all$odor,matrix_all$prediction), mean)
      figure <- ggplot(cmatrix, aes(x=prediction, y=odor, fill=value)) +
        geom_tile() + theme_bw() + coord_equal() +
        scale_fill_distiller(palette="Greens", direction=1,limits=c(0, 80) ) +
        guides(fill="none") + # removing legend for `fill`
        labs(title = paste(ana,r,sep = "_")) + # using a title instead
        geom_text(aes(label=value), color="black") # printing values
      print(figure)
    }
  }
}
```
