---
output: html_document
params:
    path: "/Volumes/WD_F/gufei/blind/"
    roi: !r c('Amy8_at165','Pir_new_at165','Pir_old_at165','APC_new_at165','APC_old_at165','PPC_at165','EarlyV_at165','V1_at165','V2_at165','V3_at165')
    roiname: !r c("Amy","Pir_new","Pir_old","APC_new","APC_old","PPC","EarlyV","V1","V2","V3")
    sub: !r c(sprintf('S%02d',c(2:4,6:14,16)))
    suffix: "_tent_12.txt"
title: "ROIs"
author: "Fei"
date: "`r Sys.time()`"
---

<style>
.html-widget {
    margin: auto;
}
</style>

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning = T, message = F, cache = FALSE,tidy=F,fig.align='center',fig.showtext=TRUE,results="hold",fig.show = "hold")
library(bruceR)
library(psych)
library(ggplot2)
library(ggthemr)
library(RColorBrewer)
library(ggpubr)
library(ggrepel)
library(plotly)
library(R.matlab)
library(plyr)
library(dplyr)
library(tidyr)
library(ggprism)
ggthemr('fresh',layout = "clean")
```

```{r include=FALSE}
# array of odors
odors <- c("gas","ind","ros","pin","app","min","fru","flo")
pd <- position_dodge(0)
roi_color <- c("#1F78B4", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6", "#00441B", "#A1D99B", "#41AB5D", "#006D2C")
gf_color <- c("#412d21", "#777DDD", "#cf7ced", "#ECB556", "#dc0922", "#4292C6", "#e45869", "#41AB5D")
pd <- position_dodge(0.1)
##################################################
# function to extract time courses from txt file
##################################################
extractdata <- function(txtname){
# use comment.char = "" to avoid problems caused by "#"
data <- read.table(txtname,header = TRUE,comment.char = "",
                   colClasses = c("character","character","NULL","character"),
                   col.names = c("sub","TimePoints","Null","NZmean"))
# 去掉每个被试开头的标题的那一行
data$sub[data$sub=="File"] <- NA
data <- na.omit(data)

# data1 <- data[c(-3)]
sub <- strsplit(data$sub,"\\.")
sub <- sapply(sub,"[",2)
data$sub <- sub
#fixed = T拒绝使用正则表达式
tp <- strsplit(data$TimePoints,fixed = T,"[")
tp <- strsplit(sapply(tp,"[",2),fixed = T,"_")
data$TimePoints <- sapply(tp,"[",1)
data$NZmean <- as.numeric(data$NZmean)
roi <- strsplit(txtname,fixed = T,"/")
roi <- strsplit(sapply(roi,"[",length(roi[[1]])),fixed = T,"_p_tent")
roi <- sapply(roi,"[",1)
data <- cbind(data,rep(roi,each=nrow(data)))
names(data)[4] <- "roi"
# separate TimePoints
data1 <- separate(data,TimePoints,c("odor","time"),sep = "#")
return(data1)
}
##################################################
# function to extract voxel numbers from txt file
##################################################
extractvoxel <- function(txtname){
# use comment.char = "" to avoid problems caused by "#"
data <- read.table(txtname,header = TRUE,comment.char = "")
# 去掉每个被试开头的标题的那一行
data$File[data$sub=="File"] <- NA
data <- na.omit(data)
# extract useful columns
data <- data[seq(4,ncol(data),2)]
# extract sub name
sub <- sapply(strsplit(txtname,fixed=T,"/"),"[",7)
data <- cbind(sub,data)
# change column names
setnames(data, old = c("NZcount_1","NZcount_3","NZcount_5","NZcount_6","NZcount_7","NZcount_8","NZcount_9","NZcount_10","NZcount_15"), new = roi_9, skip_absent=TRUE)
# change to num
data[2:ncol(data)] <- as.numeric(data[2:ncol(data)])
# calculate 3 regions
data <- mutate(data, BaLa=Ba+La+AB+PL,CeMe=Ce+Me,Cortical=Co+CAT,Amy=BaLa+CeMe+Cortical+AAA)
# names(data)[1] <- "sub"
return(data)
}
##################################################
# function to smooth time course
##################################################
tc_smooth <- function(data_tent){
  # dcast data to wide format
  times <- 1:length(unique(data_tent$time))
  data_tent$time <- factor(data_tent$time,levels = as.character(times-1))
  stent <- reshape2::dcast(data_tent,sub+roi+odor~time,value.var = "NZmean")
  # pad the edge (weighted average)
  time_data <- t(stent[,-1:-3])
  time_data <- zoo::rollapply(rbind(time_data[1,],time_data,time_data[nrow(time_data),]),3,mean)
  stent[,-1:-3] <- t(time_data)
  # use the 2 points at the edge
  # time_data <- rbind(apply(time_data[1:2,], 2, mean),
  #                     zoo::rollapply(time_data,3,mean),
  #                     apply(time_data[nrow(time_data)-1:nrow(time_data),], 2, mean))
  tc_smooth <- reshape2::melt(stent,c("sub","roi","odor"),value.name = "NZmean")
  # change column name
  tc_smooth <- dplyr::rename(tc_smooth,time = variable)
}
```
# Ratings

```{r fig.height=4, fig.width=7}
# WORD_SIZE <- 14
pd <- position_dodge(0)
# read mat file
data <- readMat(file.path(params$path,'rating_mri.mat'))
# avgdata is a dataframe
avgdata <- as.data.frame(data$mriresults)
# add subject name as row.names
row.names(avgdata) <- sprintf("S%02d", avgdata[,1])
# select subject in params$sub
avgdata <- avgdata[rownames(avgdata) %in% params$sub,]
names(avgdata) <- c("sub","sex","age","aware",
                    paste(rep(c("va","in","fa"),times = 6),rep(odors[1:6],each = 3),sep = "_"),
                    paste("vivid",odors,sep = "_"),
                    paste(paste0(rep("run",48),rep(1:6,each = 8)),odors,sep = "_"))
avgdata <- as.data.table(avgdata)
# export to spss
bruceR::export(avgdata, file = paste0(path,"ratings.sav"))
# melt to long format
rundata <- separate(melt(id.vars="sub",avgdata[,c(1,31:78)]),variable,c("run","odor"),sep = "_")
avgdata <- separate(melt(id.vars="sub",avgdata[,c(1,5:30)]),variable,c("dimension","odor"),sep = "_")
# 建立一个list保存plotyly的结果
plotly_plots <- htmltools::tagList()
i <- 1
for (dim in unique(avgdata$dimension)) {
  if (dim=="vivid")
    ymax <- 4
  else
    ymax <- 7
  current <- subset(avgdata,dimension==dim)
  analyze_current <- describeBy(current$value,list(current$odor),mat = TRUE)
  datachosen <- subset(analyze_current,select = c(group1,mean,se))
  names(datachosen) <- c("odor","mean","se")
  datachosen <- mutate(datachosen,odor = factor(odor,odors))
    figure <- ggplot(datachosen,aes(x=odor,y=mean,group=odor)) + 
    labs(title = str_to_title(dim) ,x='Odor',y=dim)+#设置坐标轴
    scale_y_continuous(expand = c(0,0))+
    coord_cartesian(ylim=c(1,ymax)) + 
    scale_fill_manual(values = gf_color)+ #自选颜色
    geom_bar(position="dodge", stat="identity")+
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.2,color='black',
                  position=position_dodge(.9))
    pfigure <- figure + theme_prism(base_line_size = 0.5)
    print(pfigure)
    
    # boxplot
    current <- mutate(current,odor = factor(odor,odors))
    figure <- ggplot(current,aes(x=odor,y=value,label=sub,
                                    group=odor)) + 
    labs(title = str_to_title(dim) ,x='Odor',y=dim)+#设置坐标轴
    scale_y_continuous(expand = c(0,0))+
    coord_cartesian(ylim=c(1,ymax)) + 
    geom_boxplot() +
    scale_fill_manual(values = gf_color)+ #自选颜色
    geom_point(col=2,pch=16,cex=1)+
    theme_prism(base_line_size = 0.5)

    print(figure)
    # interactive plots
    plotly_plots[[dim]][[i]] <- ggplotly(figure,tooltip = c("label","y"))%>%layout(boxmode="group")
    i <- i+1
    
    # ANOVA
    cat(paste0("\n\n",dim,"\n\n"))
    bruceR::MANOVA(current,subID = "sub",dv = "value", within = "odor")%>%
      EMMEANS("odor", p.adjust="fdr")
}
#输出交互式绘图的结果
plotly_plots
```

```{r fig.height=3, fig.width=5}
# vividness per run
analyze_vivid <- describeBy(rundata$value,list(rundata$run,rundata$odor),mat = TRUE)

# Intensity
datachosen <- subset(analyze_vivid,select = c(group1,group2,mean,se))
names(datachosen) <- c("run","odor","mean","se")
datachosen <- mutate(datachosen,odor = factor(odor,odors))
title <- "Vividness"
figure_int <- ggplot(datachosen, aes(x=run, y=mean,color=odor,group=odor)) + 
  labs(title = title ,x='Run',y='Vividness',color='Odor')+#设置坐标轴
  scale_y_continuous(expand = c(0,0))+
  scale_fill_manual(values = gf_color)+ #颜色
  scale_color_manual(values = gf_color)+ #自选颜色
  scale_x_discrete(labels=as.character(1:6),expand = c(0,0))+
  # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
  geom_line(position = pd) +
  # use linetype=0 or color=NA to remove border
  geom_ribbon(aes(ymin = mean - se,
                  ymax = mean + se,fill = odor), alpha = 0.1,linetype=0)+
  guides(fill = "none",color = guide_legend(
    order = 1,# set legend order
    override.aes = list(fill = gf_color)))+
  coord_cartesian(ylim=c(1,4),clip = 'off')+
  geom_point(position = pd)
# print(figure_int)
pfigure <- figure_int + theme_prism(base_line_size = 0.5)
print(pfigure)
# ANOVA
bruceR::MANOVA(rundata,subID = "sub",dv = "value", within = c("odor","run"))%>%
  EMMEANS("run", by = "odor", p.adjust="fdr")
```

# Time course

## load data
```{r}
# data_tent stores time courses for each subject and each region
data_tent <- data.frame(sub=0,odor=0,time=0,NZmean=0,roi=0)
data_tent <- data_tent[-1,]
for (sub_i in params$sub) {
  # file path
  name <- file.path(params$path,"stats",sub_i,paste0(params$roi,'_p',params$suffix))
  for (region in 1:length(name)) {
  data_tent <- rbind(data_tent,extractdata(name[region]))
  }
}
# smooth data
data_tent <- tc_smooth(data_tent)
```

## Separate
```{r echo=TRUE}
for (sub_i in params$sub) {
  for (region in params$roi) {
  # choose data
  datachosen <- subset(data_tent,sub==sub_i & roi==region)
  # set time and odor levels
  datachosen$time <- factor(datachosen$time,levels = as.character(c(0:12)))
  datachosen$odor <- factor(datachosen$odor,levels = odors)
  # plot time course
  figure_4 <- ggplot(datachosen, aes(x=time, y=NZmean,color=odor,group=odor)) + 
    labs(title = paste(sub_i,region,sep = "_"),
         x='Time(s)',y='Percent of signal change (%)',color='Odor')+#设置坐标轴
    scale_y_continuous(expand = c(0,0))+
    coord_cartesian(ylim=c(min(datachosen$NZmean)-1,max(datachosen$NZmean+1))) + 
    # scale_fill_manual(values = colors[1:2])+ #颜色
    scale_color_manual(values = gf_color)+ #自选颜色
    scale_x_discrete(expand = c(0,0.1))+
    geom_line(position = pd) +
    geom_hline(yintercept=0, linetype="dotted")+
    geom_point(position = pd)
  # print(figure_4)
  pfigure <- figure_4 + theme_prism(base_line_size = 0.5)
  print(pfigure)
}
}
```

## Average sub
```{r}
for (region in c(params$roi,"All")) {
# choose data
  if (region =="All")
    datachosen <- subset(data_tent,roi%in%params$roi[c(1,5)])
  else
    datachosen <- subset(data_tent,roi==region)
  datachosen <- describeBy(datachosen$NZmean,list(datachosen$odor,datachosen$time),mat = T)
  datachosen <- subset(datachosen,select = c(group1,group2,mean,se))
  names(datachosen) <- c("odor","time","mean","se")
  # set time and odor levels
  datachosen$time <- factor(datachosen$time,levels = as.character(c(0:12))) 
  datachosen$odor <- factor(datachosen$odor,levels = odors)
  # plot time course
  figure_4 <- ggplot(datachosen, aes(x=time, y=mean,color=odor,group=odor)) + 
    labs(title = paste(region,sep = "_"),
         x='Time(s)',y='Percent of signal change (%)',color='odor')+#设置坐标轴
    scale_y_continuous(expand = c(0,0))+
    # coord_cartesian(ylim=c(min(datachosen$mean)-0.1,max(datachosen$mean+0.1))) + 
    # scale_fill_manual(values = colors[1:2])+ #颜色
    scale_color_manual(values = gf_color)+ #自选颜色
    scale_fill_manual(values = gf_color)+ #自选颜色
    scale_x_discrete(expand = c(0,0.1))+
    geom_line(position = pd) +
    geom_hline(yintercept=0, linetype="dotted")+
    # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
    geom_ribbon(aes(ymin = mean - se, ymax = mean + se, fill = odor), 
                alpha = 0.2,linetype=0)+
    geom_point(position = pd)
  # print(figure_4)
  pfigure <- figure_4 + theme_prism(base_line_size = 0.5)
  print(pfigure)
}
```

## Average sub and odor
```{r}
# store tent for each roi
roi_tent <- data.frame(matrix(ncol = 4, nrow = 0))
for (region in params$roi) {
# choose data
datachosen <- subset(data_tent,roi==region)
# average by odors first so that df for standard error is number of subs
datachosen <- aggregate(datachosen$NZmean, list(datachosen$sub,datachosen$roi,datachosen$time), FUN=mean)
datachosen <- describeBy(datachosen$x,list(datachosen$Group.3),mat = T)
datachosen <- subset(datachosen,select = c(group1,mean,se))
names(datachosen) <- c("time","mean","se")
# set time and odor levels
datachosen$time <- factor(datachosen$time,levels = as.character(c(0:12)))

# # plot time course
# figure_4 <- ggplot(datachosen, aes(x=time, y=mean,group=1)) + 
#   labs(title = paste("All",region,sep = "_"),
#        x='Time(s)',y='Percent of signal change (%)')+#设置坐标轴
#   scale_y_continuous(expand = c(0,0))+
#   coord_cartesian(ylim=c(min(datachosen$mean)-1,max(datachosen$mean+1)),
#                   clip = 'off') + 
#   scale_fill_manual(values = gf_color)+ #颜色
#   scale_color_manual(values = gf_color)+ #自选颜色
#   scale_x_discrete(expand = c(0,0))+
#   geom_line(position = pd) +
#   geom_hline(yintercept=0, linetype="dotted")+
#   geom_ribbon(aes(ymin = mean - se,
#                   ymax = mean + se), alpha = 0.2)+
#   # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
#   geom_point(position = pd)
# # print(figure_4)
# pfigure <- figure_4 + theme_prism(base_line_size = 0.5)
# print(pfigure)

# save datachosen to roi_tent
datachosen <- cbind(datachosen,rep(region,each=nrow(datachosen)))
roi_tent <- rbind(roi_tent,datachosen)
}
# change name
names(roi_tent)[4] <- "roi"
# set levels
roi_tent$roi <- factor(roi_tent$roi,levels = params$roi,labels = params$roiname)

# plot
figure_roi <- ggplot(roi_tent, aes(x=time, y=mean,group=roi,color=roi)) + 
  labs(x='Time(s)',y='Percent of signal change (%)')+#设置坐标轴
  scale_y_continuous(expand = c(0,0))+
  coord_cartesian(ylim=c(min(roi_tent$mean)-0.1,max(roi_tent$mean+0.1)),
                  clip = 'off') + 
  scale_color_manual(values = roi_color)+ #自选颜色
  scale_fill_manual(values = roi_color)+ #自选颜色
  scale_x_discrete(expand = c(0,0))+
  geom_line(position = pd) +
  geom_hline(yintercept=0, linetype="dotted")+
  # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1,position = pd) +
  geom_ribbon(aes(ymin = mean - se, ymax = mean + se, fill = roi),
              alpha = 0.2,linetype=0)+
  geom_point(position = pd)
# print(figure_4)
pfigure <- figure_roi + theme_prism(base_line_size = 0.5)
print(pfigure)
```
