---
title: "generTiming"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, cache = TRUE)
```


```{r}
setwd("/Volumes/WD_D/Exp_odor_face/fMRI\ data_supplemental/timingtxt_two")
timing <- seq(18,392*5,16)
write.table(timing,file = "baseline.txt")
```

判断是否存在baseline.1D
```{bash}
cd /Volumes/WD_D/Exp_odor_face/fMRI\ data_supplemental/timingtxt_two
if [ ! -e baseline.1D ]
then
  echo no baseline.1D
  touch baseline.1D
else
  echo baseline.1D exists
fi
```

生成baseline.1D
空白的部分的时间点每个被试都是一样的，都是从第18s开始，然后间隔16s（刺激是从第8s开始间隔16s）
```{bash}
cd /Volumes/WD_D/Exp_odor_face/fMRI\ data_supplemental/timingtxt_two
# 5个run
for run in $(seq 1 5)
do
  # 开头4个tr不算，为0
  for i in $(seq 1 4)
  do
    echo 0
  done
  # 24个trial
  for i in $(seq 1 24)
  do
    # 5个tr是有刺激的，为0
    for j in $(seq 1 5)
    do
      echo 0
    done
    # 3个tr是没有刺激的，为1
    for k in $(seq 1 3)
    do
      echo 1
    done
  done 
done > baseline.1D

cat baseline.1D | wc -l
# for i in {1..100..2}; do echo $i; done
```
使用matlab转换
```{bash}
cd /Volumes/WD_D/Exp_odor_face/fMRI\ data_supplemental/timingtxt_two
export PATH=$PATH:/Applications/MATLAB_R2016b.app/bin/
matlab -nojvm -r "timing_trans;quit"
```
转移位置
```{bash}
cd /Volumes/WD_D/Exp_odor_face/fMRI\ data_supplemental/timingtxt_two
cp baseline.txt ../timingtxt/
cp baseline.1D ../Timings/
mv baseline.txt /Volumes/WD_D/allsub/timingtxt/
mv baseline.1D /Volumes/WD_D/allsub/timing/
```

